using System;
using System.Collections.Generic;
using UnityEngine;

public class AchievementManager : SingletonMonoBehaviour
{
	public const string KEY_PREFIX = "player.achievement.";

	public Achievements m_srcAchievements;

	public GameObject m_ToasterPrefab;

	private AchievementToast m_Toaster;

	private Dictionary<string, Achievements.AchievementData> m_achievementData = new Dictionary<string, Achievements.AchievementData>();

	public static AchievementManager Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<AchievementManager>();
		}
	}

	private void Start()
	{
		LoadAchievements();
		MobileNetworkManager.playerAuthenticated += OnPlayerAuthenticated;
		MobileNetworkManager.achievementsLoaded += OnAchievementsLoaded;
		GameObject gameObject = UnityEngine.Object.Instantiate(m_ToasterPrefab) as GameObject;
		m_Toaster = gameObject.GetComponent<AchievementToast>();
	}

	private void OnDisable()
	{
		MobileNetworkManager.playerAuthenticated -= OnPlayerAuthenticated;
		MobileNetworkManager.achievementsLoaded -= OnAchievementsLoaded;
	}

	public int GetStep(string Id)
	{
		int result = 0;
		Achievements.AchievementData value;
		if (m_achievementData.TryGetValue(Id, out value))
		{
			result = value.Step;
		}
		return result;
	}

	public int GetStepCount(string Id)
	{
		int result = 0;
		Achievements.AchievementData value;
		if (m_achievementData.TryGetValue(Id, out value))
		{
			result = value.nSteps;
		}
		return result;
	}

	public float GetPercentComplete(string Id)
	{
		float result = 0f;
		Achievements.AchievementData value;
		if (m_achievementData.TryGetValue(Id, out value))
		{
			result = (float)Math.Floor((double)((float)value.Step * 100f) / (double)value.nSteps);
		}
		return result;
	}

	public void SetPercentComplete(string Id, float PercentComplete)
	{
		int step = (int)(PercentComplete / 100f * (float)GetStepCount(Id));
		SetStep(Id, step);
	}

	public bool IsOneShot(string Id)
	{
		return Id.StartsWith("oneshot");
	}

	public bool IsDistinction(string Id)
	{
		return Id.StartsWith("distinction");
	}

	public bool IsCompleted(string Id)
	{
		bool result = false;
		Achievements.AchievementData value;
		if (m_achievementData.TryGetValue(Id, out value))
		{
			result = value.Step == value.nSteps;
		}
		return result;
	}

	public void SetCompleted(string Id)
	{
		Achievements.AchievementData value;
		if (m_achievementData.TryGetValue(Id, out value))
		{
			SetStep(Id, value.nSteps);
		}
	}

	public void ResetAll()
	{
		Debug.Log("RESETTING ACHIEVEMENTS");
		MobileNetworkManager.Instance.resetAchievements();
		foreach (Achievements.AchievementData value in m_achievementData.Values)
		{
			value.Step = 0;
			PlayerPrefs.SetInt("player.achievement." + value.Identifier, 0);
		}
	}

	public void SetStep(string Id, int Step, bool localOnly)
	{
		Achievements.AchievementData value;
		if (!m_achievementData.TryGetValue(Id, out value))
		{
			return;
		}
		if (Step > value.nSteps)
		{
			Step = value.nSteps;
		}
		if (Step != value.Step)
		{
			value.Step = Step;
			PlayerPrefs.SetInt("player.achievement." + Id, Step);
			float num = ((value.Step != value.nSteps) ? (100f * (float)value.Step / (float)value.nSteps) : 100f);
			if (!localOnly && MobileNetworkManager.Instance.SupportsAchievements && MobileNetworkManager.Instance.IsLoggedIn)
			{
				MobileNetworkManager.Instance.reportAchievement(value.Identifier, num);
			}
			if (m_Toaster != null && num >= 100f)
			{
				m_Toaster.Kick(Id);
			}
		}
	}

	public void SetStep(string Id, int Step)
	{
		SetStep(Id, Step, false);
	}

	public void IncrementStep(string Id)
	{
		int step = GetStep(Id);
		SetStep(Id, step + 1);
	}

	public void IncrementStepBy(string Id, int Inc)
	{
		int step = GetStep(Id);
		SetStep(Id, step + Inc);
	}

	private void LoadAchievements()
	{
		Achievements.AchievementData[] achievements = m_srcAchievements.achievements;
		foreach (Achievements.AchievementData achievementData in achievements)
		{
			Achievements.AchievementData achievementData2 = new Achievements.AchievementData();
			achievementData2.Identifier = achievementData.Identifier;
			achievementData2.Name = achievementData.Name;
			achievementData2.PreEarnedDesc = achievementData.PreEarnedDesc;
			achievementData2.EarnedDesc = achievementData.EarnedDesc;
			achievementData2.nSteps = achievementData.nSteps;
			achievementData2.Step = PlayerPrefs.GetInt("player.achievement." + achievementData.Identifier);
			m_achievementData[achievementData.Identifier] = achievementData2;
		}
	}

	private void OnPlayerAuthenticated()
	{
		if (!TBFUtils.Is256mbDevice() && MobileNetworkManager.Instance.SupportsAchievements)
		{
			MobileNetworkManager.Instance.getAchievements();
		}
	}

	public Achievements.AchievementData GetAchievementById(string id)
	{
		Achievements.AchievementData value = null;
		m_achievementData.TryGetValue(id, out value);
		return value;
	}

	private void OnAchievementsLoaded(List<MobileNetworkAchievement> NetworkAchievements)
	{
		if (TBFUtils.Is256mbDevice())
		{
			return;
		}
		Debug.Log("*** OnAchievementsLoaded Begin ***");
		foreach (Achievements.AchievementData value in m_achievementData.Values)
		{
			float num = ((value.Step != value.nSteps) ? (100f * (float)value.Step / (float)value.nSteps) : 100f);
			float num2 = 0f;
			foreach (MobileNetworkAchievement NetworkAchievement in NetworkAchievements)
			{
				if (NetworkAchievement.AchievementID == value.Identifier)
				{
					num2 = NetworkAchievement.PercentComplete;
					break;
				}
			}
			Debug.Log("--- Ach: " + value.Identifier + ", local = " + num + ", net = " + num2);
			if (num > num2)
			{
				Debug.Log("Updating network achievement " + value.Identifier + " to " + value.Step + "/" + value.nSteps);
				MobileNetworkManager.Instance.reportAchievement(value.Identifier, num, false);
			}
			else if (num2 > num)
			{
				Debug.Log("Updating local achievement " + value.Identifier + " to " + num2 + "%");
				int step = (int)(num2 / 100f * (float)GetStepCount(value.Identifier));
				SetStep(value.Identifier, step, true);
			}
		}
		PlayerPrefs.Save();
		Debug.Log("*** OnAchievementsLoaded End ***");
	}

	public void SanityCheckUberAchievement()
	{
		Achievements.AchievementData[] achievements = m_srcAchievements.achievements;
		foreach (Achievements.AchievementData achievementData in achievements)
		{
			if ((achievementData.Version == 1 || achievementData.Version == 2) && achievementData.Identifier != "accum.complete" && achievementData.Identifier != "accum.completedroid" && !IsCompleted(achievementData.Identifier))
			{
				return;
			}
		}
		if (Application.platform == RuntimePlatform.IPhonePlayer)
		{
			SetCompleted("accum.complete");
		}
		else
		{
			SetCompleted("accum.completedroid");
		}
	}
}
