using System.Collections;
using System.Text;
using UnityEngine;

public class BedrockWorker : SingletonMonoBehaviour
{
	public static uint MAX_LEADERROWS_TO_PULL = 10u;

	private bool m_PullingScores;

	private Bedrock.brLeaderboardRow[] m_LastResult = new Bedrock.brLeaderboardRow[MAX_LEADERROWS_TO_PULL];

	public Bedrock.brLeaderboardRow[] ResultStore
	{
		get
		{
			return m_LastResult;
		}
		set
		{
			m_LastResult = value;
		}
	}

	public bool IsPullingScores
	{
		get
		{
			return m_PullingScores;
		}
	}

	public static BedrockWorker Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<BedrockWorker>();
		}
	}

	protected override void AwakeOnce()
	{
		Object.DontDestroyOnLoad(this);
		TBFUtils.DebugLog("Bedrock Worker Alive");
	}

	public IEnumerator UpdateTask(short taskHandle, string name)
	{
		if (taskHandle != -1)
		{
			BedrockTask task = new BedrockTask(taskHandle);
			yield return StartCoroutine(task.WaitForTaskToCompleteOrTimeoutCoroutine());
			Bedrock.brTaskStatus taskStatus = Bedrock.getTaskStatus(taskHandle);
			if (taskStatus == Bedrock.brTaskStatus.BR_TASK_SUCCESS)
			{
				Debug.Log(name + " task succeeded.");
			}
			else
			{
				int errorCode = Bedrock.getTaskErrorCode(taskHandle);
				Debug.Log(name + " task failed: " + taskStatus.ToString() + " ErrorCode=" + errorCode);
			}
			Bedrock.ReleaseTaskHandle(ref taskHandle);
		}
		else
		{
			Debug.LogError("Unable to update invalid task");
		}
	}

	public IEnumerator UpdateReadTask(short taskHandle, string name)
	{
		yield return StartCoroutine(Instance.UpdateTask(taskHandle, name));
		m_PullingScores = false;
		Bedrock.brLeaderboardRow[] lastResult = m_LastResult;
		for (int i = 0; i < lastResult.Length; i++)
		{
			Bedrock.brLeaderboardRow row = lastResult[i];
			Debug.Log("ROW: " + row._rank + "USER: " + row.getEntityName());
		}
		Bedrock.GetLeaderboardResults(taskHandle, m_LastResult, MAX_LEADERROWS_TO_PULL, false);
		Bedrock.brLeaderboardRow[] lastResult2 = m_LastResult;
		for (int j = 0; j < lastResult2.Length; j++)
		{
			Bedrock.brLeaderboardRow row2 = lastResult2[j];
			Debug.Log(">>> ROW: " + row2._rank + "USER: " + row2.getEntityName());
		}
	}

	public void WriteLeaderboardValue(uint iLeaderBoard, int iValue0, Bedrock.brLeaderboardWriteType eWriteType)
	{
		Bedrock.brLeaderboardRow[] array = new Bedrock.brLeaderboardRow[1];
		array[0]._leaderboardId = iLeaderBoard;
		array[0]._userId = Bedrock.getAnonymousUserId();
		UTF8Encoding uTF8Encoding = new UTF8Encoding();
		byte[] bytes = uTF8Encoding.GetBytes(MobileNetworkManager.Instance.PlayerAlias);
		array[0]._entityName = bytes;
		array[0]._writeType = eWriteType;
		array[0]._rating = 1L;
		array[0]._floatFields = new float[5];
		array[0]._integerFields = new int[5];
		array[0]._integerFields[0] = iValue0;
		Debug.Log(string.Concat("Writing Leaderboard ", iLeaderBoard, " for ", array[0]._entityName, " with score ", iValue0));
		StartCoroutine("WriteLeaderboardTask", array);
	}

	private IEnumerator WriteLeaderboardTask(Bedrock.brLeaderboardRow[] rows)
	{
		int iRetryAttempts = 10;
		do
		{
			short taskHandle = Bedrock.StartWriteToLeaderboardRequest(Bedrock.brLobbyServerTier.BR_LOBBY_SERVER_TITLE, Bedrock.getAnonymousUserId(), rows);
			if (taskHandle != -1)
			{
				yield return StartCoroutine(Instance.UpdateTask(taskHandle, "Write Leaderboard"));
				iRetryAttempts = 0;
				continue;
			}
			Debug.Log("Awaiting Retry");
			yield return new WaitForSeconds(5f);
			iRetryAttempts--;
			if (iRetryAttempts == 0)
			{
				Debug.LogError("Failed to Create WriteLeaderboardTask Task");
			}
		}
		while (iRetryAttempts > 0);
	}

	public void GetLeaderboardValuesByRank(uint uiLeaderboard, ulong ulRank)
	{
		if (!m_PullingScores)
		{
			StartCoroutine(GetLeaderboardValuesByRankTask(uiLeaderboard, ulRank));
		}
		else
		{
			Debug.LogError("Attempting to pull leaderboards while already pulling");
		}
	}

	private IEnumerator GetLeaderboardValuesByRankTask(uint uiLeaderboard, ulong ulRank)
	{
		int iRetryAttempts = 10;
		do
		{
			short taskHandle = Bedrock.StartReadLeaderboardByRank(Bedrock.brLobbyServerTier.BR_LOBBY_SERVER_TITLE, uiLeaderboard, Bedrock.getAnonymousUserId(), ulRank, MAX_LEADERROWS_TO_PULL);
			if (taskHandle != -1)
			{
				m_PullingScores = true;
				yield return StartCoroutine(Instance.UpdateReadTask(taskHandle, "Read Leaderboard by Rank"));
				iRetryAttempts = 0;
				continue;
			}
			Debug.Log("Awaiting Retry");
			yield return new WaitForSeconds(5f);
			iRetryAttempts--;
			if (iRetryAttempts == 0)
			{
				Debug.LogError("Failed to Create GetLeaderboardValuesByRank Task");
			}
		}
		while (iRetryAttempts > 0);
	}
}
