using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DialogManager : SingletonMonoBehaviour
{
	public class InterstitialAdEntry
	{
		public string m_name;

		public string m_url;

		public float m_frequency;
	}

	private const string m_reviewURL = "itms-apps://ax.itunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?type=Purple+Software&id={0}";

	private const string OptShowMe = "S_SHOW_ME";

	private const string OptNoThanks = "S_NO_THANKS";

	private const string BigCatTitle = "S_PR_BIG_CAT_TITLE";

	private const string BigCatBody = "S_PR_BIG_CAT_BODY";

	private const string RespawnTitle = "S_PR_RESPAWN_TITLE";

	private const string RespawnBody = "S_PR_RESPAWN_BODY";

	private const string PoisonTitle = "S_UP_POISON_T";

	private const string PoisionBody = "S_PR_POISON_BODY";

	private const string AntiVenomTitle = "S_PR_ANTIVENOM_TITLE";

	private const string AntiVenomBody = "S_PR_ANTIVENOM_BODY";

	private const string SpeedTitle = "S_PR_SPEED_TITLE";

	private const string SpeedBody = "S_PR_SPEED_BODY";

	private const string CostumeTitle = "S_ACH_A_FASHIONISTA";

	private const string CostumeBody = "S_PR_COSTUME_BODY";

	private const string LoseMacawTitle = "S_LOSE_MACAW_TITLE";

	private const string LoseMacawBody = "S_LOSE_MACAW_BODY";

	private const string LoseMacawOpt1 = "S_LOSE_MACAW_OPT1";

	private const string BuyMacawTitle = "S_BUY_MACAW_TITLE";

	private const string BuyMacawBody = "S_BUY_MACAW_BODY";

	private const string BuyMacawOpt1 = "S_BUY_MACAW_OPT1";

	private const string RateAppTitle = "S_RATEAPP_TITLE";

	private const string RateAppBody = "S_RATEAPP_BODY";

	private const string RateAppOptRate = "S_RATEAPP_OPT_RATE";

	private const string RateAppOptRem = "S_RATEAPP_OPT_REMIND";

	private const string SilverGoldTitle = "S_PR_TREASURE_UPG_TITLE";

	private const string SilverGoldBody = "S_PR_TREASURE_UPG_BODY";

	private const string BuyCheckpointTitle = "S_CHECK_TUT_1_TITLE";

	private const string BuyCheckpointBody = "S_CHECK_TUT_1_BODY";

	private const string WarnMacawTitle = "S_WARN_MACAW_TITLE";

	private const string WarnMacawBody = "S_WARN_MACAW_BODY";

	private const string NewCheckpointTitle = "S_CHECKPOINT_NEW_TITLE";

	private const string NewCheckpointBody = "S_CHECKPOINT_NEW_BODY";

	private const string FacebookTitle = "S_FACEBOOK_LIKE_TITLE";

	private const string FacebookBody = "S_FACEBOOK_LIKE_BODY";

	private const string FacebookOpt1 = "S_FACEBOOK_LIKE_OPT_LIKE";

	private const string FacebookOpt2 = "S_FACEBOOK_LIKE_OPT_REMIND";

	private const string TapjoyUnlockTitle = "TapjoyOffersUnlockedDialog";

	private const string TapjoyHalfwayUnlockTitle = "TapjoyOffersHalfwayUnlockedDialog";

	public ConfirmDialog m_standardDialogPrefab;

	public ConfirmDialog m_rateAppDialogPrefab;

	public ConfirmDialog m_noButtonDialogPrefab;

	public MessageBox m_standardMessageBoxPrefab;

	public BigMessage m_rewardsDialogPrefab;

	public WhatsNewDialog m_whatsNewDialogPrefab;

	public OutfitOfTheDayInfoDialog m_ootdInfoDialogPrefab;

	public NewSaleDialog m_newSaleDialogPrefab;

	public DiamondsToContinueDialog m_diamondsToContinueDialogPrefab;

	public DiamondsOrAdvertsToContinueDialog m_diamondsOrAdvertsToContinueDialogPrefab;

	public Countdown m_countDownPrefab;

	public string m_firstCheckpoint = "checkpoint.2000";

	public string m_6kCheckpoint = "checkpoint.6000";

	public string m_macawConsumable = "consumable.macaw";

	public string m_jaguarUpgrade = "upgrade.jaguar";

	public string m_spiritJungleConsumable = "consumable.jungle";

	public string m_poisonUpgrade = "upgrade.poison";

	public string m_antiVenomConsumable = "consumable.antivenom";

	public string m_speedIncreaseConsumable = "consumable.speedincrease";

	public string m_firstOutfit = "outfit.ninja";

	[HideInInspector]
	public BaseCampProducts[] m_products;

	private string m_lastDialogSpawed;

	private BaseCampProducts.ProductData m_storeFocusProduct;

	private bool m_hasSeenUpdateDialogThisBoot;

	private static int s_iDialogTicker;

	private int m_intervalBetweenInterstitials = 5;

	private List<InterstitialAdEntry> m_interstitials = new List<InterstitialAdEntry>();

	public static bool DialogActive
	{
		get
		{
			SwrveTalkComponent instance = SwrveTalkComponent.Instance;
			if (instance != null && instance.IsMessageDispaying())
			{
				return true;
			}
			return s_iDialogTicker > 0;
		}
	}

	public static DialogManager Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<DialogManager>();
		}
	}

	public static void DialogLock()
	{
		s_iDialogTicker++;
	}

	public static void DialogUnlock()
	{
		s_iDialogTicker--;
	}

	public static void ResetCounter()
	{
		s_iDialogTicker = 0;
	}

	private void Start()
	{
	}

	public bool LaunchGameEndDialogs()
	{
		if (!IsSwrveActive())
		{
			if (BaseCampController.Instance.TutorialActive())
			{
				return false;
			}
			if (LaunchAppUpdateDialog())
			{
				return true;
			}
			bool flag = false;
			if (GameController.Instance != null)
			{
				flag = GameController.Instance.IsPlayingTrialsMode;
			}
			if (!flag && LaunchCheckpointRecommendations())
			{
				return true;
			}
			if (flag)
			{
				if (LaunchSocialDialogs())
				{
					return true;
				}
				if (LaunchPurchaseRecommendations())
				{
					return true;
				}
			}
			return false;
		}
		return false;
	}

	private bool IsSwrveActive()
	{
		SwrveTalkComponent instance = SwrveTalkComponent.Instance;
		if (instance != null && instance.IsMessageDispaying())
		{
			return true;
		}
		return false;
	}

	public bool LaunchTitleDialogs()
	{
		if (!IsSwrveActive())
		{
			if (LaunchAppUpdateDialog())
			{
				return true;
			}
			if (LaunchNewSaleDialog())
			{
				return true;
			}
		}
		return false;
	}

	public bool LaunchCheckpointRecommendations()
	{
		if (!IsSwrveActive())
		{
			if (CheckFirstCheckpoint())
			{
				return true;
			}
			if (CheckBuyMacawDialog())
			{
				return true;
			}
		}
		return false;
	}

	public bool CheckFirstCheckpoint()
	{
		bool result = false;
		SecureStorage instance = SecureStorage.Instance;
		if (instance.GetDialogViewedCount("S_CHECK_TUT_1_TITLE") <= 0 && instance.IsCheckpointUnlocked(m_firstCheckpoint) && instance.GetItemCount(m_firstCheckpoint) == 0 && !BaseCampController.Instance.TutorialActive())
		{
			GameObject tutorialButton = GameObject.Find("StoreIcon");
			StartCoroutine(SpawnCheckpointTutorialDialog("S_CHECK_TUT_1_TITLE", "S_CHECK_TUT_1_BODY", tutorialButton));
			BaseCampController.Instance.SetTutorialActive();
			result = true;
		}
		return result;
	}

	public IEnumerator SpawnFirstCheckpointDialog()
	{
		yield return StartCoroutine(SpawnStoreItemDialog("S_CHECK_TUT_1_TITLE", "S_CHECK_TUT_1_BODY", m_firstCheckpoint));
	}

	public bool LaunchNoMccawDialog()
	{
		if (!IsSwrveActive())
		{
			string text;
			string message;
			string opt;
			string opt2;
			if ((bool)CheckPointController.Instance() && CheckPointController.Instance().HasPlayerPassedValidCheckpoint())
			{
				text = "S_BUY_MACAW_TITLE";
				message = Language.Get("S_BUY_MACAW_BODY");
				opt = Language.Get("S_OK");
				opt2 = Language.Get("S_OK");
			}
			else
			{
				text = "S_WHAT_IS_MACAW_TITLE";
				message = Language.Get("S_WHAT_IS_MACAW_BODY");
				opt = Language.Get("S_OK");
				opt2 = Language.Get("S_OK");
			}
			ConfirmDialog confirmDialog = (ConfirmDialog)UnityEngine.Object.Instantiate(m_standardDialogPrefab);
			StartCoroutine(confirmDialog.Display(Language.Get(text), message, opt, opt2, null, null, null, text, null));
			return true;
		}
		return false;
	}

	private bool HasEnoughTimePassed(int DialogLevel)
	{
		int lastDialogGamesPlayedCount = SecureStorage.Instance.LastDialogGamesPlayedCount;
		int gamesPlayed = SecureStorage.Instance.GamesPlayed;
		return gamesPlayed - lastDialogGamesPlayedCount >= DialogLevel;
	}

	public bool LaunchSocialDialogs()
	{
		if (!IsSwrveActive())
		{
			int gamesPlayed = SecureStorage.Instance.GamesPlayed;
			if (gamesPlayed < 5)
			{
				return false;
			}
			if (CheckFacebookDialog())
			{
				return true;
			}
		}
		return false;
	}

	public bool CheckFacebookDialog()
	{
		bool result = false;
		if (!TBFUtils.Is256mbDevice() && SwrveServerVariables.Instance.RatingReward > 0)
		{
			SecureStorage instance = SecureStorage.Instance;
			bool hasToldFacebookFriends = instance.HasToldFacebookFriends;
			bool flag = instance.GetDialogViewedCount("S_FACEBOOK_LIKE_TITLE") > 0;
			if (!hasToldFacebookFriends && !flag)
			{
				StartCoroutine("SpawnFacebookLike");
				result = true;
			}
		}
		return result;
	}

	public IEnumerator SpawnFacebookLike()
	{
		yield return StartCoroutine(SpawnStandardDialog("S_FACEBOOK_LIKE_TITLE", "S_FACEBOOK_LIKE_BODY", "S_FACEBOOK_LIKE_OPT_LIKE", "S_FACEBOOK_LIKE_OPT_REMIND", OnFacebookYes, DummyCallback, DummyCallback));
	}

	public void OnFacebookYes()
	{
		TellFacebookFriends();
	}

	public void TellFacebookFriends()
	{
		string text = Language.Get("S_FACEBOOK_POST");
		string caption = text;
		string appStoreURI = SwrveServerVariables.Instance.AppStoreURI;
		string linkName = Language.Get("S_FACEBOOK_POST_NAME");
		string description = Language.Get("S_FACEBOOK_POST_DESC");
		string imageURI = SwrveServerVariables.Instance.ImageURI;
		if (MobileNetworkManager.Instance.PostToFacebook(caption, appStoreURI, linkName, description, imageURI) && !SecureStorage.Instance.HasToldFacebookFriends)
		{
			StartCoroutine(RewardPlayer(SwrveServerVariables.Instance.RatingReward));
			SecureStorage.Instance.HasToldFacebookFriends = true;
		}
	}

	public void TellTwitterFollowers()
	{
		string text = Language.Get("S_TWITTER_POST");
		text += " ";
		text += SwrveServerVariables.Instance.AppShortURI;
		if (MobileNetworkManager.Instance.PostToTwitter(text) && !SecureStorage.Instance.HasToldTwitterFollowers)
		{
			StartCoroutine(RewardPlayer(SwrveServerVariables.Instance.RatingReward));
			SecureStorage.Instance.HasToldTwitterFollowers = true;
		}
	}

	private IEnumerator RewardPlayer(int nCoins)
	{
		if (nCoins > 0)
		{
			yield return new WaitForSeconds(1f);
			SecureStorage.Instance.ChangeCoins(nCoins);
			string Title = Language.Get("S_THANKS");
			string Body = "x " + nCoins;
			BigMessage levelUpMessage = (BigMessage)UnityEngine.Object.Instantiate(m_rewardsDialogPrefab);
			yield return StartCoroutine(levelUpMessage.Display(Title, Body, 3f));
		}
		yield return null;
	}

	public bool LaunchPurchaseRecommendations()
	{
		if (!IsSwrveActive())
		{
			int gamesPlayed = SecureStorage.Instance.GamesPlayed;
			if (gamesPlayed < 6)
			{
				return false;
			}
			if (CheckBigCatDialog())
			{
				return true;
			}
			if (CheckRespawnDialog())
			{
				return true;
			}
			if (CheckPoisonImmunityDialog())
			{
				return true;
			}
			if (CheckAntiVenomDialog())
			{
				return true;
			}
			if (CheckSpeedUpgradeDialog())
			{
				return true;
			}
			if (CheckSilverGoldDialog())
			{
				return true;
			}
			if (CheckCostumeDialog())
			{
				return true;
			}
		}
		return false;
	}

	public bool CheckBuyMacawDialog()
	{
		bool result = false;
		SecureStorage instance = SecureStorage.Instance;
		if (instance.GetDialogViewedCount("S_BUY_MACAW_TITLE") <= 0 && instance.LastDistanceTravelled > CheckPointController.Instance().FirstCheckPointDistance() && SecureStorage.Instance.GetItemCount("consumable.macaw") == 0)
		{
			StartCoroutine("SpawnBuyMacawDialog");
			result = true;
		}
		return result;
	}

	public bool CheckBigCatDialog()
	{
		bool result = false;
		SecureStorage instance = SecureStorage.Instance;
		if (instance.GetDialogViewedCount("S_PR_BIG_CAT_TITLE") <= 0 && HasEnoughTimePassed(2))
		{
			int lastJaguarCount = instance.LastJaguarCount;
			int itemCount = instance.GetItemCount(m_jaguarUpgrade);
			if (lastJaguarCount == 1 && itemCount == 0)
			{
				StartCoroutine("SpawnBigCatDialog");
				result = true;
			}
		}
		return result;
	}

	public IEnumerator SpawnBigCatDialog()
	{
		yield return StartCoroutine(SpawnStoreItemDialog("S_PR_BIG_CAT_TITLE", "S_PR_BIG_CAT_BODY", m_jaguarUpgrade));
	}

	public bool CheckRespawnDialog()
	{
		bool result = false;
		SecureStorage instance = SecureStorage.Instance;
		if (instance.GetDialogViewedCount("S_PR_RESPAWN_TITLE") <= 0 && HasEnoughTimePassed(2))
		{
			int itemCount = instance.GetItemCount(m_spiritJungleConsumable);
			if (instance.GamesPlayed >= 10 && itemCount == 0)
			{
				StartCoroutine("SpawnRespawnDialog");
				result = true;
			}
		}
		return result;
	}

	public IEnumerator SpawnRespawnDialog()
	{
		yield return StartCoroutine(SpawnStoreItemDialog("S_PR_RESPAWN_TITLE", "S_PR_RESPAWN_BODY", m_spiritJungleConsumable));
	}

	public bool CheckPoisonImmunityDialog()
	{
		bool result = false;
		SecureStorage instance = SecureStorage.Instance;
		if (instance.GetDialogViewedCount("S_UP_POISON_T") <= 0 && HasEnoughTimePassed(2) && instance.GetItemCount(m_poisonUpgrade) == 0 && PlayerController.Instance().LastKillType() == PieceDescriptor.KillType.Poison)
		{
			StartCoroutine("SpawnPoisonImmunityDialog");
			result = true;
		}
		return result;
	}

	public IEnumerator SpawnPoisonImmunityDialog()
	{
		yield return StartCoroutine(SpawnStoreItemDialog("S_UP_POISON_T", "S_PR_POISON_BODY", m_poisonUpgrade));
	}

	public bool CheckAntiVenomDialog()
	{
		bool result = false;
		SecureStorage instance = SecureStorage.Instance;
		if (instance.GetDialogViewedCount("S_PR_ANTIVENOM_TITLE") <= 0 && HasEnoughTimePassed(2) && instance.GetItemCount(m_antiVenomConsumable) == 0 && PlayerController.Instance().LastKillType() == PieceDescriptor.KillType.Poison)
		{
			StartCoroutine("SpawnAntiVenomDialog");
			result = true;
		}
		return result;
	}

	public IEnumerator SpawnAntiVenomDialog()
	{
		yield return StartCoroutine(SpawnStoreItemDialog("S_PR_ANTIVENOM_TITLE", "S_PR_ANTIVENOM_BODY", m_antiVenomConsumable));
	}

	public bool CheckSpeedUpgradeDialog()
	{
		bool result = false;
		SecureStorage instance = SecureStorage.Instance;
		if (instance.GetDialogViewedCount("S_PR_SPEED_TITLE") <= 0 && HasEnoughTimePassed(2) && instance.GetItemCount(m_speedIncreaseConsumable) == 0 && PlayerController.Instance() != null)
		{
			float num = PlayerController.Instance().Score().DistanceTravelled();
			if (num >= 10000f)
			{
				StartCoroutine("SpawnSpeedUpgradeDialog");
				result = true;
			}
		}
		return result;
	}

	public IEnumerator SpawnSpeedUpgradeDialog()
	{
		yield return StartCoroutine(SpawnStoreItemDialog("S_PR_SPEED_TITLE", "S_PR_SPEED_BODY", m_speedIncreaseConsumable));
	}

	private bool HasBoughtCostume()
	{
		return SecureStorage.Instance.GetCostumesBought() > 0;
	}

	public bool CheckCostumeDialog()
	{
		bool result = false;
		SecureStorage instance = SecureStorage.Instance;
		if (instance.GetDialogViewedCount("S_ACH_A_FASHIONISTA") <= 0 && HasEnoughTimePassed(3) && !HasBoughtCostume() && instance.GamesPlayed >= 35)
		{
			StartCoroutine("SpawnCostumeDialog");
			result = true;
		}
		return result;
	}

	public IEnumerator SpawnCostumeDialog()
	{
		yield return StartCoroutine(SpawnStoreItemDialog("S_ACH_A_FASHIONISTA", "S_PR_COSTUME_BODY", m_firstOutfit));
	}

	public IEnumerator SpawnBuyMacawDialog()
	{
		yield return StartCoroutine(SpawnStoreItemDialog("S_BUY_MACAW_TITLE", "S_BUY_MACAW_BODY", m_macawConsumable));
	}

	public bool CheckSilverGoldDialog()
	{
		bool result = false;
		SecureStorage instance = SecureStorage.Instance;
		if (instance.GetDialogViewedCount("S_PR_TREASURE_UPG_TITLE") <= 0 && HasEnoughTimePassed(3))
		{
			bool flag = instance.GetItemCount(StoreProductManager.TreasureUpgradeIdentifier) > 0;
			if (instance.GamesPlayed >= 20 && !flag)
			{
				StartCoroutine(SpawnExchangeItemDialog("S_PR_TREASURE_UPG_TITLE", "S_PR_TREASURE_UPG_BODY", StoreProductManager.TreasureUpgradeIdentifier));
				result = true;
			}
		}
		return result;
	}

	public bool AskLoseMacawQuestion(Action OnYes, Action OnNo, bool Show)
	{
		if (!IsSwrveActive())
		{
			bool result = false;
			SecureStorage instance = SecureStorage.Instance;
			if (!Show)
			{
				return result;
			}
			if (instance.LastDistanceTravelled > CheckPointController.Instance().FirstCheckPointDistance())
			{
				if (instance.HasMacaws)
				{
					StartCoroutine(SpawnLoseMacawDialog(OnYes, OnNo));
					result = true;
				}
				else
				{
					StartCoroutine(SpawnWarnCheckpointLost(OnNo));
					result = true;
				}
			}
			return result;
		}
		return false;
	}

	public bool AskBuyNewCheckpointQuestion(bool Show)
	{
		if (!IsSwrveActive())
		{
			bool result = false;
			SecureStorage instance = SecureStorage.Instance;
			if (!Show)
			{
				return result;
			}
			if ((bool)BaseCampController.Instance && BaseCampController.Instance.TutorialActive())
			{
				return false;
			}
			if (instance.HasMacaws)
			{
				int purchasableCheckpointImmediatelyPrevious = CheckPointController.Instance().GetPurchasableCheckpointImmediatelyPrevious();
				if (purchasableCheckpointImmediatelyPrevious > 0)
				{
					string text = "checkpoint." + purchasableCheckpointImmediatelyPrevious;
					BaseCampProducts.ProductData productData = StoreProductManager.Instance.FindProduct(text);
					if (productData.GemsPrice(0) <= SecureStorage.Instance.GetGems())
					{
						StartCoroutine(SpawnStoreItemDialog("S_CHECKPOINT_NEW_TITLE", "S_CHECKPOINT_NEW_BODY", text));
						result = true;
					}
				}
			}
			return result;
		}
		return false;
	}

	public IEnumerator SpawnLoseMacawDialog(Action OnYes, Action OnNo)
	{
		yield return StartCoroutine(SpawnStandardDialog("S_LOSE_MACAW_TITLE", "S_LOSE_MACAW_BODY", "S_LOSE_MACAW_OPT1", "S_NO_THANKS", OnYes, OnNo, OnNo));
	}

	public IEnumerator SpawnWarnCheckpointLost(Action OnNo)
	{
		m_storeFocusProduct = StoreProductManager.Instance.FindProduct(m_macawConsumable);
		yield return StartCoroutine(SpawnStandardDialog("S_WARN_MACAW_TITLE", "S_WARN_MACAW_BODY", "S_SHOW_ME", "S_NO_THANKS", LaunchStoreCallback, OnNo, OnNo));
	}

	public bool CheckRateAppDialog()
	{
		if (TBFUtils.Is256mbDevice() || SwrveServerVariables.Instance.RatingReward <= 0)
		{
			return false;
		}
		SecureStorage instance = SecureStorage.Instance;
		if (instance.LastRatedVersion == TBFUtils.BundleVersion)
		{
			TBFUtils.DebugLog("ALREADY RATED: " + instance.LastRatedVersion + ", " + TBFUtils.BundleVersion);
			return false;
		}
		int timesRatingChecked = instance.TimesRatingChecked;
		timesRatingChecked = (instance.TimesRatingChecked = timesRatingChecked + 1);
		TBFUtils.DebugLog("TIMES CHECKED: " + timesRatingChecked);
		int num2 = instance.CheckedBetweenRaing;
		if (num2 == 0 || instance.LastCheckedVersion != TBFUtils.BundleVersion)
		{
			instance.CheckedBetweenRaing = SwrveServerVariables.Instance.ChecksBetweenRating;
			num2 = SwrveServerVariables.Instance.ChecksBetweenRating;
		}
		TBFUtils.DebugLog("CHECKED COUNT: " + num2);
		instance.LastCheckedVersion = TBFUtils.BundleVersion;
		if (timesRatingChecked < num2)
		{
			return false;
		}
		if (!HasEnoughTimePassed(3))
		{
			return false;
		}
		StartCoroutine("SpawnRateAppDialog");
		return true;
	}

	private void LaunchAppRating()
	{
		TBFUtils.DebugLog("LAUNCH APP RATING");
		SecureStorage.Instance.LastRatedVersion = TBFUtils.BundleVersion;
		TBFUtils.LaunchStoreForRating();
		StartCoroutine(RewardPlayer(SwrveServerVariables.Instance.RatingReward));
	}

	private void RateLater()
	{
		TBFUtils.DebugLog("RATE LATER");
		int checkedBetweenRaing = SecureStorage.Instance.CheckedBetweenRaing;
		SecureStorage.Instance.CheckedBetweenRaing = checkedBetweenRaing * 2;
	}

	public IEnumerator SpawnRateAppDialog()
	{
		yield return StartCoroutine(SpawnPrefabDialog(m_rateAppDialogPrefab, "S_RATEAPP_TITLE", "S_RATEAPP_BODY", "S_RATEAPP_OPT_RATE", "S_RATEAPP_OPT_REMIND", LaunchAppRating, RateLater, RateLater, null));
	}

	private bool ParseAppVersionNumbers(string versionString, out int versionNumber, out int revisionNumber)
	{
		bool result = false;
		versionNumber = 0;
		revisionNumber = 0;
		char[] separator = new char[1] { '.' };
		string[] array = versionString.Split(separator, StringSplitOptions.RemoveEmptyEntries);
		if (array.Length >= 2)
		{
			result = int.TryParse(array[0], out versionNumber);
			result = int.TryParse(array[1], out revisionNumber) && result;
		}
		return result;
	}

	public bool IsNewAppVersionAvailable()
	{
		bool result = false;
		if (SwrveServerVariables.Instance != null)
		{
			string appVersion = SwrveServerVariables.Instance.AppVersion;
			int versionNumber = 0;
			int revisionNumber = 0;
			ParseAppVersionNumbers(appVersion, out versionNumber, out revisionNumber);
			string vERSION = StartGameSettings.Instance.VERSION;
			int versionNumber2 = 0;
			int revisionNumber2 = 0;
			ParseAppVersionNumbers(vERSION, out versionNumber2, out revisionNumber2);
			if (versionNumber > versionNumber2 || (versionNumber == versionNumber2 && revisionNumber > revisionNumber2))
			{
				result = true;
			}
		}
		return result;
	}

	public bool LaunchAppUpdateDialog()
	{
		if (!IsSwrveActive())
		{
			bool result = false;
			if (IsNewAppVersionAvailable() && !m_hasSeenUpdateDialogThisBoot)
			{
				string titleKey = "S_PR_UPDATE_TITLE";
				string bodyKey = "S_PR_UPDATE_BODY";
				string opt1Key = "S_PR_UPDATE_BUTTON";
				string empty = string.Empty;
				StartCoroutine(SpawnStandardDialog(titleKey, bodyKey, opt1Key, empty, LaunchUpdateApp, DummyCallback, DummyCallback));
				m_hasSeenUpdateDialogThisBoot = true;
				result = true;
			}
			return result;
		}
		return false;
	}

	private void LaunchUpdateApp()
	{
		if (SwrveServerVariables.Instance != null)
		{
			TBFUtils.DebugLog("LAUNCHING APP UPDATE");
			TBFUtils.LaunchURL(SwrveServerVariables.Instance.AppShortURI);
		}
	}

	public bool LaunchWhatsNewDialog()
	{
		if (!IsSwrveActive())
		{
			bool result = false;
			SecureStorage instance = SecureStorage.Instance;
			string dialogName = "S_WHATS_NEW";
			if (instance.GetDialogViewedCount(dialogName) <= 0)
			{
				WhatsNewDialog whatsNewDialog = (WhatsNewDialog)UnityEngine.Object.Instantiate(m_whatsNewDialogPrefab);
				StartCoroutine(whatsNewDialog.Display());
				instance.IncDialogViewedCount(dialogName);
				result = true;
			}
			return result;
		}
		return false;
	}

	public bool LaunchOOTDDialog()
	{
		if (!IsSwrveActive())
		{
			OutfitOfTheDayInfoDialog outfitOfTheDayInfoDialog = (OutfitOfTheDayInfoDialog)UnityEngine.Object.Instantiate(m_ootdInfoDialogPrefab);
			StartCoroutine(outfitOfTheDayInfoDialog.Display());
			return true;
		}
		return false;
	}

	public bool LaunchNewSaleDialog()
	{
		if (!IsSwrveActive())
		{
			bool result = false;
			if (StoreProductManager.Instance.IsSaleActive)
			{
				string lastSaleSeen = SecureStorage.Instance.LastSaleSeen;
				string identifier = StoreProductManager.Instance.SaleItem.Identifier;
				if (identifier != lastSaleSeen)
				{
					SecureStorage.Instance.LastSaleSeen = identifier;
					NewSaleDialog newSaleDialog = (NewSaleDialog)UnityEngine.Object.Instantiate(m_newSaleDialogPrefab);
					StartCoroutine(newSaleDialog.Display());
					result = true;
				}
			}
			else
			{
				SecureStorage.Instance.LastSaleSeen = string.Empty;
			}
			return result;
		}
		return false;
	}

	private void LaunchStoreCallback()
	{
		if (m_storeFocusProduct != null)
		{
			TBFUtils.DebugLog("Launching Store with " + m_storeFocusProduct.Identifier);
			if (BaseCampController.Instance != null)
			{
				BaseCampController.Instance.LaunchWithProductFocus(m_storeFocusProduct);
			}
		}
	}

	private void DummyCallback()
	{
		TBFUtils.DebugLog("Dummy Callback");
	}

	private IEnumerator SpawnStoreItemDialog(string TitleKey, string BodyKey, string focusProduct)
	{
		m_storeFocusProduct = StoreProductManager.Instance.FindProduct(focusProduct);
		if (m_storeFocusProduct != null)
		{
			yield return StartCoroutine(SpawnStandardDialog(TitleKey, BodyKey, "S_SHOW_ME", string.Empty, LaunchStoreCallback, DummyCallback, DummyCallback));
		}
		else
		{
			yield return null;
		}
	}

	private IEnumerator SpawnCheckpointTutorialDialog(string TitleKey, string BodyKey, GameObject tutorialButton)
	{
		yield return StartCoroutine(SpawnPrefabDialog(m_noButtonDialogPrefab, TitleKey, BodyKey, string.Empty, string.Empty, DummyCallback, DummyCallback, DummyCallback, tutorialButton));
	}

	public DiamondsToContinueDialog LaunchDiamondsToContinueDialog(bool ShowCountDown)
	{
		DiamondsToContinueDialog diamondsToContinueDialog = (DiamondsToContinueDialog)UnityEngine.Object.Instantiate(m_diamondsToContinueDialogPrefab);
		StartCoroutine(diamondsToContinueDialog.Display(ShowCountDown));
		return diamondsToContinueDialog;
	}

	public DiamondsOrAdvertsToContinueDialog LaunchDiamondsOrAdvertsToContinueDialog(bool ShowCountDown)
	{
		DiamondsOrAdvertsToContinueDialog diamondsOrAdvertsToContinueDialog = (DiamondsOrAdvertsToContinueDialog)UnityEngine.Object.Instantiate(m_diamondsOrAdvertsToContinueDialogPrefab);
		StartCoroutine(diamondsOrAdvertsToContinueDialog.Display(ShowCountDown));
		return diamondsOrAdvertsToContinueDialog;
	}

	private void LaunchExchangeCallback()
	{
		if (BaseCampController.Instance != null)
		{
			BaseCampController.Instance.LaunchWithExchangeFocus();
		}
	}

	private IEnumerator SpawnExchangeItemDialog(string TitleKey, string BodyKey, string focusProduct)
	{
		m_storeFocusProduct = null;
		yield return StartCoroutine(SpawnStandardDialog(TitleKey, BodyKey, "S_SHOW_ME", string.Empty, LaunchExchangeCallback, DummyCallback, DummyCallback));
	}

	public void SpawnDialog(string TitleKey, string BodyKey, string Opt1Key, string Opt2Key, Action OnYes, Action OnNo, Action OnCancel)
	{
		ConfirmDialog confirmDialog = (ConfirmDialog)UnityEngine.Object.Instantiate(m_standardDialogPrefab);
		StartCoroutine(confirmDialog.Display(TitleKey, BodyKey, Opt1Key, Opt2Key, OnYes, OnNo, OnCancel, TitleKey, null));
	}

	private IEnumerator SpawnStandardDialog(string TitleKey, string BodyKey, string Opt1Key, string Opt2Key, Action OnYes, Action OnNo, Action OnCancel)
	{
		yield return StartCoroutine(SpawnPrefabDialog(m_standardDialogPrefab, TitleKey, BodyKey, Opt1Key, Opt2Key, OnYes, OnNo, OnCancel, null));
	}

	private IEnumerator SpawnPrefabDialog(ConfirmDialog dialogPrefab, string TitleKey, string BodyKey, string Opt1Key, string Opt2Key, Action OnYes, Action OnNo, Action OnCancel, GameObject tutorialButton)
	{
		m_lastDialogSpawed = TitleKey;
		SecureStorage.Instance.IncDialogViewedCount(TitleKey);
		SecureStorage.Instance.LastDialogGamesPlayedCount = SecureStorage.Instance.GamesPlayed;
		ConfirmDialog confirmDialog = (ConfirmDialog)UnityEngine.Object.Instantiate(dialogPrefab);
		string Title = Language.Get(TitleKey);
		string Body = Language.Get(BodyKey);
		string Opt1 = Language.Get(Opt1Key);
		string Opt2 = Language.Get(Opt2Key);
		yield return StartCoroutine(confirmDialog.Display(Title, Body, Opt1, Opt2, OnYes, OnNo, OnCancel, TitleKey, tutorialButton));
	}

	private IEnumerator SpawnPrefabMessageBox(MessageBox msgBoxPrefab, string TitleKey, string BodyKey, string OptKey)
	{
		m_lastDialogSpawed = TitleKey;
		SecureStorage.Instance.IncDialogViewedCount(TitleKey);
		SecureStorage.Instance.LastDialogGamesPlayedCount = SecureStorage.Instance.GamesPlayed;
		MessageBox msgBox = (MessageBox)UnityEngine.Object.Instantiate(m_standardMessageBoxPrefab);
		string Title = Language.Get(TitleKey);
		string Body = Language.Get(BodyKey);
		string Option = Language.Get(OptKey);
		yield return StartCoroutine(msgBox.Display(Title, Body, Option));
	}

	public void LaunchCountdown(Action onComplete)
	{
		Countdown countdown = (Countdown)UnityEngine.Object.Instantiate(m_countDownPrefab);
		StartCoroutine(countdown.DisplayCountdown(onComplete));
	}

	private IEnumerator DialogTest()
	{
		yield return StartCoroutine("LaunchAppUpdateDialog");
		yield return StartCoroutine("SpawnBuyMacawDialog");
		yield return StartCoroutine("SpawnFacebookLike");
		yield return StartCoroutine("SpawnBigCatDialog");
		yield return StartCoroutine("SpawnRespawnDialog");
		yield return StartCoroutine("SpawnPoisonImmunityDialog");
		yield return StartCoroutine("SpawnAntiVenomDialog");
		yield return StartCoroutine("SpawnSpeedUpgradeDialog");
		yield return StartCoroutine("SpawnCostumeDialog");
		yield return StartCoroutine(SpawnLoseMacawDialog(DummyCallback, DummyCallback));
		yield return StartCoroutine(SpawnWarnCheckpointLost(DummyCallback));
		yield return StartCoroutine("SpawnRateAppDialog");
		yield return StartCoroutine(SpawnExchangeItemDialog("S_PR_TREASURE_UPG_TITLE", "S_PR_TREASURE_UPG_BODY", string.Empty));
	}

	private void SetupTestInterstitials()
	{
		InterstitialAdEntry interstitialAdEntry = new InterstitialAdEntry();
		interstitialAdEntry.m_name = "Wipeout";
		interstitialAdEntry.m_url = "http://funhatch.pwp.blueyonder.co.uk/interstitial/wipeout";
		interstitialAdEntry.m_frequency = 0.35f;
		m_interstitials.Add(interstitialAdEntry);
		interstitialAdEntry = new InterstitialAdEntry();
		interstitialAdEntry.m_name = "Anthology";
		interstitialAdEntry.m_url = "http://funhatch.pwp.blueyonder.co.uk/interstitial/anthology";
		interstitialAdEntry.m_frequency = 0.35f;
		m_interstitials.Add(interstitialAdEntry);
		interstitialAdEntry = new InterstitialAdEntry();
		interstitialAdEntry.m_name = "BOZ";
		interstitialAdEntry.m_url = "http://funhatch.pwp.blueyonder.co.uk/interstitial/boz";
		interstitialAdEntry.m_frequency = 0.35f;
		m_interstitials.Add(interstitialAdEntry);
	}

	private bool LaunchInterstitial()
	{
		if (m_interstitials.Count == 0 || TBFUtils.Is256mbDevice())
		{
			return false;
		}
		SecureStorage instance = SecureStorage.Instance;
		InterstitialAdEntry interstitialAdEntry = null;
		float num = float.MinValue;
		int num2 = int.MaxValue;
		for (int i = 0; i < m_interstitials.Count; i++)
		{
			InterstitialAdEntry interstitialAdEntry2 = m_interstitials[i];
			float interstitialAdvertWeight = instance.GetInterstitialAdvertWeight(interstitialAdEntry2.m_name);
			int interstitialAdvertViewedCount = instance.GetInterstitialAdvertViewedCount(interstitialAdEntry2.m_name);
			interstitialAdvertWeight += interstitialAdEntry2.m_frequency;
			if (interstitialAdvertWeight > 1f)
			{
				bool flag = false;
				if (interstitialAdvertWeight > num)
				{
					flag = true;
				}
				else if (interstitialAdvertWeight == num)
				{
					flag = interstitialAdvertViewedCount < num2;
				}
				if (flag)
				{
					interstitialAdEntry = interstitialAdEntry2;
					num = interstitialAdvertWeight;
					num2 = interstitialAdvertViewedCount;
				}
			}
			instance.SetInterstitialAdvertWeight(interstitialAdEntry2.m_name, interstitialAdvertWeight);
		}
		if (!instance.HasInterstitialCountdown)
		{
			instance.InterstitialCountdown = m_intervalBetweenInterstitials;
		}
		if (--instance.InterstitialCountdown > 0)
		{
			return false;
		}
		if (interstitialAdEntry == null)
		{
			return false;
		}
		if (Application.internetReachability == NetworkReachability.NotReachable)
		{
			return false;
		}
		instance.InterstitialCountdown = m_intervalBetweenInterstitials;
		instance.SetInterstitialAdvertWeight(interstitialAdEntry.m_name, 0f);
		instance.IncIntersitialAdvertViewedCount(interstitialAdEntry.m_name);
		TBFUtils.DebugLog("INTERSTITIAL: " + interstitialAdEntry.m_name);
		TBFUtils.ShowInterstitialAd(interstitialAdEntry.m_url, "pitfall");
		return true;
	}

	public void UpdateFromBedrock()
	{
		List<InterstitialAdEntry> list = new List<InterstitialAdEntry>();
		int num = 10;
		for (int i = 0; i < num; i++)
		{
			string itemId = string.Format("interstitial{0}", i);
			Dictionary<string, string> resourceDictionary = null;
			if (Bedrock.GetRemoteUserResources(itemId, out resourceDictionary))
			{
				string fromResourceDictionaryAsString = Bedrock.GetFromResourceDictionaryAsString(resourceDictionary, "name", string.Empty);
				string fromResourceDictionaryAsString2 = Bedrock.GetFromResourceDictionaryAsString(resourceDictionary, "url", string.Empty);
				float fromResourceDictionaryAsFloat = Bedrock.GetFromResourceDictionaryAsFloat(resourceDictionary, "weight", -1f);
				if (!string.IsNullOrEmpty(fromResourceDictionaryAsString) && !string.IsNullOrEmpty(fromResourceDictionaryAsString2) && fromResourceDictionaryAsFloat > 0f)
				{
					TBFUtils.DebugLog("Read interstitial: " + fromResourceDictionaryAsString);
					InterstitialAdEntry interstitialAdEntry = new InterstitialAdEntry();
					interstitialAdEntry.m_name = fromResourceDictionaryAsString;
					interstitialAdEntry.m_url = fromResourceDictionaryAsString2;
					interstitialAdEntry.m_frequency = fromResourceDictionaryAsFloat;
					list.Add(interstitialAdEntry);
				}
			}
		}
		m_intervalBetweenInterstitials = Bedrock.GetRemoteVariableAsInt("interstitialCountdown", m_intervalBetweenInterstitials);
		TBFUtils.DebugLog("SWRVE - interval between interstitials: " + m_intervalBetweenInterstitials);
		m_interstitials = list;
		TBFUtils.DebugLog("SWRVE - received " + m_interstitials.Count + " intersitials");
	}
}
