public class EnvironmentSFX : SFXBank
{
	public SoundFXData HouseExplode;

	public SoundFXData TreeCollapse;

	public SoundFXData Impact;

	public SoundFXData LogRoll;

	public SoundFXData SpikeEject;

	public SoundFXData WoodBreakImpact;

	public SoundFXData WoodBridgeCollapse;

	public SoundFXData WoodBridgeDestroyed;

	public SoundFXData Waterfall;

	public SoundFXData BigRockDestroy;

	public SoundFXData CartWoosh;

	public SoundFXData FirePit;

	public SoundFXData CaveTileWind;

	public SoundFXData MineBell;

	public static EnvironmentSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<EnvironmentSFX>();
		}
	}
}
