using UnityEngine;

public class GameTutorial : SingletonMonoBehaviour
{
	public float m_loadAheadDistance = 50f;

	public TutorialDialog m_dialogPrefab;

	private bool m_Enabled;

	private TutorialMessageData m_Finish = new TutorialMessageData("S_TUTORIAL_MESSAGE_END");

	private TutorialMessageData[] m_WellDone = new TutorialMessageData[4]
	{
		new TutorialMessageData("S_TUT_CONGRATS_1"),
		new TutorialMessageData("S_TUT_CONGRATS_2"),
		new TutorialMessageData("S_TUT_CONGRATS_3"),
		new TutorialMessageData("S_TUT_CONGRATS_4")
	};

	private TutorialMessageData m_Poison = new TutorialMessageData("S_TUTORIAL_MESSAGE_POISON");

	private TutorialMessageData m_AntiVenom = new TutorialMessageData("S_TUTORIAL_MESSAGE_POISON_ANTIV");

	private TutorialMessageData m_TryAgain = new TutorialMessageData("S_TUT_TRY_AGAIN");

	private TutorialMessageData m_TurnApproaching = new TutorialMessageData("S_TUTORIAL_MESSAGE_TURN");

	private TutorialMessageData m_JumpApproaching = new TutorialMessageData("S_TUTORIAL_MESSAGE_JUMP");

	private TutorialMessageData m_DuckApproaching = new TutorialMessageData("S_TUTORIAL_MESSAGE_DUCK");

	private TutorialMessageData m_EnemyApproaching = new TutorialMessageData("S_TUTORIAL_MESSAGE_ENEMY");

	private TutorialMessageData m_TrackReductionApproaching = new TutorialMessageData("S_TUTORIAL_MESSAGE_TRACK_REDUCE");

	public static GameTutorial Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<GameTutorial>();
		}
	}

	public bool IsEnabled
	{
		get
		{
			return m_Enabled;
		}
		set
		{
			m_Enabled = value;
		}
	}

	private void Start()
	{
		Reset();
	}

	private void Show(TutorialMessageData message)
	{
		if (m_Enabled && !message.HasBeenShown())
		{
			if (m_dialogPrefab != null)
			{
				TutorialDialog tutorialDialog = (TutorialDialog)Object.Instantiate(m_dialogPrefab);
				StartCoroutine(tutorialDialog.Display(message.Text(), 2f));
			}
			message.Shown();
		}
	}

	private void ShowMisc(TutorialMessageData message)
	{
		if (m_Enabled && m_dialogPrefab != null)
		{
			TutorialDialog tutorialDialog = (TutorialDialog)Object.Instantiate(m_dialogPrefab);
			StartCoroutine(tutorialDialog.Display(message.Text(), 2f));
		}
	}

	private void Hide()
	{
	}

	public void Notify_Finish()
	{
		ShowMisc(m_Finish);
	}

	public void Notify_WellDone()
	{
		int num = Random.Range(0, m_WellDone.Length);
		ShowMisc(m_WellDone[num]);
	}

	public void Notify_Poison()
	{
		ShowMisc(m_Poison);
	}

	public void Notify_AntiVenom()
	{
		ShowMisc(m_AntiVenom);
	}

	public void Notify_TryAgain()
	{
		ShowMisc(m_TryAgain);
	}

	public void Notify_TurnApproaching()
	{
		Show(m_TurnApproaching);
	}

	public void Notify_JumpApproaching()
	{
		Show(m_JumpApproaching);
	}

	public void Notify_DuckApproaching()
	{
		Show(m_DuckApproaching);
	}

	public void Notify_EnemyApproaching()
	{
		Show(m_EnemyApproaching);
	}

	public void Notify_TrackReductionApproaching()
	{
		Show(m_TrackReductionApproaching);
	}

	public void Reset()
	{
		m_TurnApproaching.Reset();
		m_JumpApproaching.Reset();
		m_DuckApproaching.Reset();
		m_EnemyApproaching.Reset();
		m_Enabled = false;
		Hide();
	}

	private void Update()
	{
		if (!m_Enabled)
		{
		}
	}

	private bool IsJumpPiece(PieceDescriptor piece)
	{
		return piece.IsJumpPiece();
	}

	private bool IsJunctionPiece(PieceDescriptor piece)
	{
		return piece.IsJunctionPiece();
	}

	private bool IsDuckPiece(PieceDescriptor piece)
	{
		return piece.IsDuckPiece();
	}

	private bool IsBaddiePiece(PieceDescriptor piece)
	{
		return piece.IsBaddiePiece();
	}

	private bool IsTrackReductionPiece(PieceDescriptor piece)
	{
		return piece.TypeId == WorldConstructionHelper.PieceType.Pit_Type4_Entry || piece.IsTrackReductionPiece();
	}

	private void UpdateTutorialNotifications()
	{
		if (LevelGenerator.Instance() == null)
		{
			return;
		}
		float num = m_loadAheadDistance;
		PieceDescriptor pieceDescriptor = LevelGenerator.Instance().GetCurrentPiece();
		while ((bool)pieceDescriptor && num > 0f)
		{
			if (IsJumpPiece(pieceDescriptor))
			{
				Instance.Notify_JumpApproaching();
			}
			if (IsJunctionPiece(pieceDescriptor))
			{
				Instance.Notify_TurnApproaching();
			}
			if (IsDuckPiece(pieceDescriptor))
			{
				Instance.Notify_DuckApproaching();
			}
			if (IsBaddiePiece(pieceDescriptor))
			{
				Instance.Notify_EnemyApproaching();
			}
			if (IsTrackReductionPiece(pieceDescriptor))
			{
				Instance.Notify_TrackReductionApproaching();
			}
			num -= pieceDescriptor.GetLength();
			pieceDescriptor = pieceDescriptor.GetNextPiece();
		}
	}
}
