public class HarryVO : SFXBank
{
	public SoundFXData StartRun;

	public SoundFXData WhipSnake;

	public SoundFXData WhipScorpion;

	public SoundFXData WhipCroc;

	public SoundFXData RopeSwing;

	public SoundFXData StylishDismount;

	public SoundFXData StartMinecart;

	public SoundFXData StartBike;

	public SoundFXData StartJaguar;

	public static HarryVO Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<HarryVO>();
		}
	}

	public override void Play2D(string Name)
	{
		Play2D(Name, 0f);
	}

	public override void Play2D(string Name, float Delay)
	{
		if (!IsAnySoundPlaying())
		{
			base.Play2D(Name, Delay);
		}
	}
}
