public class MenuSFX : SFXBank
{
	public SoundFXData MenuPopup;

	public SoundFXData MenuCancel;

	public SoundFXData MenuBuy1;

	public SoundFXData MenuBuy2;

	public SoundFXData Swoosh;

	public SoundFXData MenuConfirm;

	public SoundFXData TabChange;

	public SoundFXData ScreenSwoosh;

	public SoundFXData Countup;

	public SoundFXData MenuBoxSwoosh;

	public SoundFXData Upgrade1;

	public SoundFXData Upgrade2;

	public SoundFXData CheckPointPurchaseAvailable;

	public SoundFXData BigMessage;

	public SoundFXData Countdown1;

	public SoundFXData Countdown2;

	public SoundFXData Countdown3;

	public SoundFXData TrialImprovement;

	public SoundFXData RelicGet;

	public SoundFXData OOTDMatch;

	public SoundFXData OOTDNoMatch;

	public SoundFXData SaleCountdown;

	public SoundFXData FlashAdditionalGemsNeeded;

	public SoundFXData DailyDoubleMarker;

	public static MenuSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<MenuSFX>();
		}
	}
}
