using UnityEngine;

public class MusicManager : SingletonMonoBehaviour
{
	public SoundFXData TitleMusic;

	public SoundFXData GameMusic;

	public SoundFXData GameOverMusic;

	private SoundFXData m_currentMusic;

	private SoundFX m_currentPlaying;

	private bool IsCurrentTrackPlaying()
	{
		return m_currentPlaying != null && m_currentPlaying.IsPlaying;
	}

	public static MusicManager Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<MusicManager>();
		}
	}

	public bool IsMuted
	{
		get
		{
			return SecureStorage.Instance.MusicMuted;
		}
		set
		{
			SecureStorage.Instance.MusicMuted = value;
			if (value)
			{
				StopMusic();
			}
			else
			{
				PlayTitleMusic();
			}
		}
	}

	private void Start()
	{
		Object.DontDestroyOnLoad(this);
	}

	public void StopMusic()
	{
		if (m_currentPlaying != null)
		{
			m_currentPlaying.Stop(base.gameObject);
			m_currentPlaying = null;
		}
		m_currentMusic = null;
	}

	public void PlayTitleMusic()
	{
		if (m_currentMusic != TitleMusic || !IsCurrentTrackPlaying())
		{
			Play(TitleMusic);
		}
	}

	public void PlayGameMusic()
	{
		if (m_currentMusic != GameMusic || !IsCurrentTrackPlaying())
		{
			Play(GameMusic);
		}
	}

	public void PlayGameOverMusic()
	{
		if (m_currentMusic != GameOverMusic || !IsCurrentTrackPlaying())
		{
			Play(GameOverMusic);
		}
	}

	private void Play(SoundFXData musicToPlay)
	{
		StopMusic();
		if (!SecureStorage.Instance.MusicMuted && !TBFUtils.IsMusicPlaying)
		{
			m_currentPlaying = new SoundFX();
			m_currentPlaying.m_sfxData = musicToPlay;
			m_currentPlaying.Play(base.gameObject, false, 1f, true);
			m_currentMusic = musicToPlay;
		}
	}

	public void Pause()
	{
		if (m_currentPlaying != null)
		{
			m_currentPlaying.Pause();
		}
	}

	public void UnPause()
	{
		if (m_currentPlaying != null)
		{
			m_currentPlaying.UnPause();
		}
	}
}
