using System;
using UnityEngine;

public class OutfitOfTheDayManager : SingletonMonoBehaviour
{
	[Serializable]
	public class OutfitDef
	{
		public Costume m_costume;

		public string m_notificationText;

		public string m_bonusText;
	}

	private const string kReminderName = "OutfitReminder";

	public OutfitDef[] m_outfitDefinitions;

	public OutfitOfTheDayMatchDialog m_matchDialogPrefab;

	public static OutfitOfTheDayManager Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<OutfitOfTheDayManager>();
		}
	}

	private int CurrentOutfitIndex
	{
		get
		{
			return GetOutfitIndexForDateTime(DateTime.Now);
		}
	}

	public Costume OOTD
	{
		get
		{
			Costume result = Costume.None;
			int currentOutfitIndex = CurrentOutfitIndex;
			if (currentOutfitIndex >= 0)
			{
				result = m_outfitDefinitions[currentOutfitIndex].m_costume;
			}
			return result;
		}
	}

	public string OotdProductIdentifier
	{
		get
		{
			Costume oOTD = OOTD;
			return SecureStorage.Instance.TranslateCostumeIdentifier(oOTD);
		}
	}

	public BaseCampProducts.ProductData OotdProduct
	{
		get
		{
			BaseCampProducts.ProductData result = null;
			string ootdProductIdentifier = OotdProductIdentifier;
			if (StoreProductManager.Instance != null)
			{
				result = StoreProductManager.Instance.FindProduct(ootdProductIdentifier);
			}
			return result;
		}
	}

	public Texture OotdTexture
	{
		get
		{
			string ootdProductIdentifier = OotdProductIdentifier;
			return StoreProductManager.LoadTextureFor(ootdProductIdentifier, 1);
		}
	}

	public string OotdBonusText
	{
		get
		{
			int currentOutfitIndex = CurrentOutfitIndex;
			return Language.Get(m_outfitDefinitions[currentOutfitIndex].m_bonusText);
		}
	}

	protected override void AwakeOnce()
	{
		base.name = "OutfitOfTheDayManager";
	}

	private int GetOutfitIndexForDateTime(DateTime timeToTest)
	{
		int result = -1;
		if (m_outfitDefinitions.Length > 0)
		{
			int num = timeToTest.WeekNumber();
			int dayOfWeek = (int)timeToTest.DayOfWeek;
			result = (dayOfWeek + num) % m_outfitDefinitions.Length;
		}
		return result;
	}

	private int FindOutfit(Costume testCostume)
	{
		int result = -1;
		for (int i = 0; i < m_outfitDefinitions.Length; i++)
		{
			if (m_outfitDefinitions[i].m_costume == testCostume)
			{
				result = i;
				break;
			}
		}
		return result;
	}

	public bool IsOOTD(Costume testCostume)
	{
		return OOTD == testCostume;
	}

	public bool IsOOTD(string Identifier)
	{
		Costume testCostume = SecureStorage.Instance.TranslateCostumeType(Identifier);
		return IsOOTD(testCostume);
	}

	public void DisplayOutfitMatchDialog()
	{
		OutfitOfTheDayMatchDialog outfitOfTheDayMatchDialog = (OutfitOfTheDayMatchDialog)UnityEngine.Object.Instantiate(m_matchDialogPrefab);
		StartCoroutine(outfitOfTheDayMatchDialog.Display(2f));
	}

	public bool BonusApplies(Costume testCostume)
	{
		bool result = false;
		if (GameController.Instance != null && !GameController.Instance.IsPlayingTrialsMode && SecureStorage.Instance.GetCurrentCostumeType() == testCostume && IsOOTD(testCostume))
		{
			result = true;
		}
		return result;
	}

	private void ScheduleOutfitReminder()
	{
	}

	private void CancelOutfitReminder()
	{
	}

	private void OnApplicationPause(bool paused)
	{
		if (paused)
		{
			ScheduleOutfitReminder();
		}
		else
		{
			CancelOutfitReminder();
		}
	}
}
