using System.Collections.Generic;
using UnityEngine;

public class SoundManager : SingletonMonoBehaviour
{
	public class DelayedSFX
	{
		public SoundFXData m_data;

		public GameObject m_source;

		public float m_playTime;
	}

	private Dictionary<SoundFXData, SoundFX> m_sfxMap = new Dictionary<SoundFXData, SoundFX>();

	private List<DelayedSFX> m_delayedSfx = new List<DelayedSFX>();

	public static SoundManager Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<SoundManager>();
		}
	}

	public bool IsMuted
	{
		get
		{
			return SecureStorage.Instance.SfxMuted;
		}
		set
		{
			SecureStorage.Instance.SfxMuted = value;
			if (value)
			{
				StopAll();
			}
		}
	}

	protected override void AwakeOnce()
	{
		Object.DontDestroyOnLoad(base.gameObject);
	}

	public void Play2D(SoundFXData fxData)
	{
		Play2D(fxData, 1f);
	}

	public void Play2D(SoundFXData fxData, float pitchOverride)
	{
		Play(fxData, null, 0f, pitchOverride);
	}

	public void Play2D(SoundFXData fxData, float pitchOverride, float delay)
	{
		Play(fxData, null, delay, pitchOverride);
	}

	public void Stop2D(SoundFXData fxData)
	{
		Stop(fxData, base.gameObject);
	}

	public void Play(SoundFXData fxData, GameObject source)
	{
		Play(fxData, source, 0f);
	}

	public void Play(SoundFXData fxData, GameObject source, float delay)
	{
		Play(fxData, source, delay, 1f);
	}

	public void Play(SoundFXData fxData, GameObject source, float delay, float pitchOverride)
	{
		if (!SecureStorage.Instance.SfxMuted && !TBFUtils.IsMusicPlaying)
		{
			if (source == null)
			{
				source = base.gameObject;
			}
			if (delay != 0f)
			{
				DelayedSFX delayedSFX = new DelayedSFX();
				delayedSFX.m_data = fxData;
				delayedSFX.m_source = source;
				delayedSFX.m_playTime = Time.realtimeSinceStartup + delay;
				m_delayedSfx.Add(delayedSFX);
			}
			else if (fxData == null)
			{
				Debug.LogWarning("No sound data while trying to play sound on " + source.name);
			}
			else
			{
				SoundFX soundEvent = GetSoundEvent(fxData);
				bool createSpeaker = source != base.gameObject;
				bool force2D = !createSpeaker;
				soundEvent.Play(source, createSpeaker, pitchOverride, force2D);
			}
		}
	}

	public void Stop(SoundFXData fxData, GameObject source)
	{
		if (fxData != null)
		{
			SoundFX value;
			if (m_sfxMap.TryGetValue(fxData, out value))
			{
				value.Stop(source);
			}
			else
			{
				RemoveDelayedSfx(fxData);
			}
		}
	}

	private SoundFX GetSoundEvent(SoundFXData FxData)
	{
		SoundFX value;
		if (!m_sfxMap.TryGetValue(FxData, out value))
		{
			value = new SoundFX();
			value.m_sfxData = FxData;
			m_sfxMap[FxData] = value;
		}
		return value;
	}

	public void SetVolume(SoundFXData fxData, GameObject source, float volume)
	{
		SoundFX value;
		if (fxData != null && m_sfxMap.TryGetValue(fxData, out value))
		{
			value.SetVolume(source, volume);
		}
	}

	public float GetVolume(SoundFXData fxData, GameObject source)
	{
		SoundFX value;
		if (fxData != null && m_sfxMap.TryGetValue(fxData, out value))
		{
			return value.GetVolume(source);
		}
		return 0f;
	}

	public void StopAll()
	{
		List<SoundFXData> list = new List<SoundFXData>();
		foreach (SoundFXData key in m_sfxMap.Keys)
		{
			list.Add(key);
		}
		foreach (SoundFXData item in list)
		{
			m_sfxMap[item].StopAll();
		}
		m_sfxMap.Clear();
		m_delayedSfx.Clear();
	}

	public bool IsPlaying(SoundFXData fxData)
	{
		bool result = false;
		if (m_sfxMap.ContainsKey(fxData))
		{
			SoundFX soundFX = m_sfxMap[fxData];
			result = soundFX.IsPlaying;
		}
		return result;
	}

	public void Pause()
	{
		foreach (SoundFX value in m_sfxMap.Values)
		{
			value.Pause();
		}
	}

	public void UnPause()
	{
		foreach (SoundFX value in m_sfxMap.Values)
		{
			value.UnPause();
		}
	}

	private void RemoveDelayedSfx(SoundFXData fxData)
	{
		DelayedSFX item = null;
		for (int i = 0; i < m_delayedSfx.Count; i++)
		{
			DelayedSFX delayedSFX = m_delayedSfx[i];
			if (delayedSFX.m_data == fxData)
			{
				item = delayedSFX;
				break;
			}
		}
		m_delayedSfx.Remove(item);
	}

	private void Update()
	{
		if (m_delayedSfx.Count <= 0)
		{
			return;
		}
		List<DelayedSFX> list = new List<DelayedSFX>();
		for (int i = 0; i < m_delayedSfx.Count; i++)
		{
			DelayedSFX delayedSFX = m_delayedSfx[i];
			if (Time.realtimeSinceStartup >= delayedSFX.m_playTime)
			{
				Play(delayedSFX.m_data, delayedSFX.m_source);
				list.Add(delayedSFX);
			}
		}
		for (int j = 0; j < list.Count; j++)
		{
			m_delayedSfx.Remove(list[j]);
		}
		list.Clear();
	}
}
