using UnityEngine;

public class SoundListener : SingletonMonoBehaviour
{
	private GameObject m_parent;

	private AudioListener m_listener;

	public static SoundListener Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<SoundListener>();
		}
	}

	protected override void AwakeOnce()
	{
		m_listener = base.gameObject.GetComponent<AudioListener>();
		if (m_listener == null)
		{
			m_listener = base.gameObject.AddComponent<AudioListener>();
		}
	}

	public void AttachTo(GameObject newParent)
	{
		if (newParent != null)
		{
			m_parent = newParent;
			base.gameObject.transform.position = m_parent.transform.position;
			base.gameObject.transform.rotation = m_parent.transform.rotation;
		}
	}

	private void Update()
	{
		if (m_parent != null && base.gameObject != null)
		{
			base.gameObject.transform.position = m_parent.transform.position;
			base.gameObject.transform.rotation = m_parent.transform.rotation;
		}
	}
}
