using UnityEngine;

public class StartGameSettings : SingletonMonoBehaviour
{
	private const string kTimerName = "TimerName";

	private const string k3DayReminderName = "3DayReminder";

	public int TargetFrameRate = 60;

	public static StartGameSettings Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<StartGameSettings>();
		}
	}

	public string VERSION
	{
		get
		{
			return TBFUtils.BuildVersion;
		}
	}

	protected override void AwakeOnce()
	{
		ApplyModernQualityDefaults();
		Application.targetFrameRate = TargetFrameRate;
		if (SecureStorage.Instance.LogFirstGameDateTime())
		{
			SwrveEventsGameplay.FirstRun();
		}
		SecureStorage.Instance.LogLastPlayedDateTime();
		EtceteraPlatformWrapper.SetBadgeCount(0);
		Object.DontDestroyOnLoad(this);
	}

	private void ApplyModernQualityDefaults()
	{
		int recommendedQualityLevel = GetRecommendedQualityLevel();
		if (recommendedQualityLevel >= 0 && QualitySettings.GetQualityLevel() != recommendedQualityLevel)
		{
			QualitySettings.SetQualityLevel(recommendedQualityLevel, applyExpensiveChanges: true);
		}
		QualitySettings.anisotropicFiltering = AnisotropicFiltering.ForceEnable;
	}

	private static int GetRecommendedQualityLevel()
	{
		string[] names = QualitySettings.names;
		if (names == null || names.Length == 0)
		{
			return -1;
		}
#if UNITY_EDITOR || UNITY_STANDALONE
		return names.Length - 1;
#else
		return Mathf.Max(names.Length - 2, 0);
#endif
	}

	public void Schedule3DayReminder()
	{
	}

	public void Cancel3DayReminder()
	{
	}

	private void OnApplicationPause(bool paused)
	{
		if (!paused)
		{
			EtceteraPlatformWrapper.SetBadgeCount(0);
		}
	}
}
