using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using HTTP;
using UnityEngine;

public class StoreProductManager : SingletonMonoBehaviour
{
	public BaseCampProducts[] m_storeProductDefs;

	public GemStoreProduct m_gemProductDefs;

	public static string TreasureUpgradeIdentifier = "treasure.permanentupgrade";

	public static string FreeGemsIdentifier = "gems.free";

	public static string Bundle1Indentifier = "gems.bundle1";

	public static string Bundle2Indentifier = "gems.bundle2";

	public static string Bundle3Indentifier = "gems.bundle3";

	public static string Bundle4Indentifier = "gems.bundle4";

	public static string Bundle1aIndentifier = "gems.bundle1a";

	public static string Bundle3aIndentifier = "gems.bundle3a";

	public static string Bundle4aIndentifier = "gems.bundle4a";

	public static string Bundle4bIndentifier = "gems.bundle4b";

	public static string Bundle5Indentifier = "gems.bundle5";

	public static string Bundle5aIndentifier = "gems.bundle5a";

	private BaseCampProducts[] m_loadedProducts;

	private GemStoreProduct m_loadedGemProducts;

	private BaseCampProducts.ProductData m_saleItem;

	private uint m_saleStart;

	private uint m_saleDuration;

	private BaseCampProducts.ProductData m_originalSaleItem;

	public string GooglePlaySecret;

	public string[] GoogleProductSkus;

	private bool m_started;

	private bool m_bSaleLocked;

	private List<GooglePurchase> mPurchases;

	private string m_receiptVerificationServerURI = string.Empty;

	private string GamePurchasedItem;

	private bool g_bIABEnabled;

	private bool g_bAwaitingBillingCallback;

	public bool SaleLocked
	{
		get
		{
			return m_bSaleLocked;
		}
		set
		{
			m_bSaleLocked = value;
		}
	}

	public static StoreProductManager Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<StoreProductManager>();
		}
	}

	public BaseCampProducts.ProductData SaleItem
	{
		get
		{
			return m_saleItem;
		}
	}

	public bool IsSaleActive
	{
		get
		{
			bool flag = false;
			if (m_saleItem != null)
			{
				uint secondsSinceUnixEpoch = TimeUtils.GetSecondsSinceUnixEpoch(DateTime.UtcNow);
				if (m_saleStart != 0 && m_saleDuration != 0)
				{
					flag = secondsSinceUnixEpoch >= m_saleStart && secondsSinceUnixEpoch < m_saleStart + m_saleDuration;
					if (!flag)
					{
						if (SaleLocked)
						{
							return true;
						}
						BaseCampProducts.ProductData toProd = FindProduct(m_saleItem.Identifier);
						m_originalSaleItem.CopyTo(toProd);
						m_saleItem = null;
					}
				}
			}
			return flag;
		}
	}

	public uint SaleTimeLeft
	{
		get
		{
			uint result = 0u;
			if (IsSaleActive)
			{
				uint secondsSinceUnixEpoch = TimeUtils.GetSecondsSinceUnixEpoch(DateTime.UtcNow);
				uint num = m_saleStart + m_saleDuration;
				result = ((secondsSinceUnixEpoch <= num) ? TimeUtils.GetSecondsSince(secondsSinceUnixEpoch, num) : 0u);
			}
			return result;
		}
	}

	public float SalePercentOff
	{
		get
		{
			float result = 0f;
			if (IsSaleActive)
			{
				float num = m_originalSaleItem.GemsPrice(0);
				float num2 = m_saleItem.GemsPrice(0);
				float num3 = (num - num2) / num * 100f;
				float num4 = m_originalSaleItem.CoinPrice(0);
				float num5 = m_saleItem.CoinPrice(0);
				float num6 = (num4 - num5) / num4 * 100f;
				result = ((!(num3 > num6)) ? num6 : num3);
				result = Mathf.Floor(result);
			}
			return result;
		}
	}

	public bool CanBuyExchangeProducts
	{
		get
		{
			if (Application.isEditor)
			{
				return true;
			}
			return g_bIABEnabled;
		}
	}

	public static event Action<bool> OnExchangeProductsReceived;

	public static event Action OnProductsUpdated;

	public static event Action<string> OnBuyExchangeSuccess;

	public static event Action<string> OnBuyExchangeFailed;

	public static event Action OnRestorePurchasesFinished;

	public static event Action<string> OnRestorePurchasesFailed;

	public static string GetResourceIDFor(string strProductIdentifier, int suffix)
	{
		if (TBFUtils.Is256mbDevice())
		{
			return string.Format("Textures/LowQual/{0}.{1:00}", strProductIdentifier, suffix);
		}
		return string.Format("Textures/{0}.{1:00}", strProductIdentifier, suffix);
	}

	public static Texture LoadTextureFor(string strProductIdentifier, int suffix)
	{
		Texture texture = null;
		if (TBFUtils.Is256mbDevice())
		{
			string path = string.Format("Textures/LowQual/{0}.{1:00}", strProductIdentifier, suffix);
			texture = Resources.Load(path) as Texture;
		}
		if (texture == null)
		{
			string path2 = string.Format("Textures/{0}.{1:00}", strProductIdentifier, suffix);
			texture = Resources.Load(path2) as Texture;
		}
		if (texture == null)
		{
			texture = Resources.Load("Textures/consumable.macaw.01") as Texture;
		}
		return texture;
	}

	private string GetReceiptVerificationURL()
	{
		string text = m_receiptVerificationServerURI;
		if (string.IsNullOrEmpty(text) || text == "null")
		{
			return string.Empty;
		}
		if (text.Contains(";"))
		{
			char[] separator = new char[1] { ';' };
			string[] array = text.Split(separator, StringSplitOptions.RemoveEmptyEntries);
			text = array[UnityEngine.Random.Range(0, array.Length)];
		}
		return text;
	}

	private string DecodeStringBase64(string encoded)
	{
		byte[] bytes = Convert.FromBase64String(encoded);
		return Encoding.UTF8.GetString(bytes);
	}

	private string EncodeStringBase64(string toencode)
	{
		ASCIIEncoding aSCIIEncoding = new ASCIIEncoding();
		byte[] bytes = aSCIIEncoding.GetBytes(toencode);
		return Convert.ToBase64String(bytes);
	}

	private void StoreLog(string message)
	{
	}

	protected override void AwakeOnce()
	{
		UnityEngine.Object.DontDestroyOnLoad(base.gameObject);
		List<string> list = new List<string>();
		if (m_gemProductDefs != null && m_gemProductDefs.products != null)
		{
			GemStoreProduct.GemStoreProductData[] products = m_gemProductDefs.products;
			foreach (GemStoreProduct.GemStoreProductData gemStoreProductData in products)
			{
				if (gemStoreProductData != null && !string.IsNullOrEmpty(gemStoreProductData.Identifier))
				{
					list.Add(gemStoreProductData.Identifier);
				}
			}
		}
		GoogleProductSkus = list.ToArray();
	}

	private void Start()
	{
		if (!m_started)
		{
			GoogleIABManager.purchaseSucceededEvent += OnPurchaseSuccessful;
			GoogleIABManager.purchaseFailedEvent += OnPurchaseFail;
			GoogleIABManager.consumePurchaseSucceededEvent += OnConsumePurchaseSuccessful;
			GoogleIABManager.consumePurchaseFailedEvent += OnConsumePurchaseFailed;
			GoogleIABManager.queryInventorySucceededEvent += OnRestoreTransactionsFinished;
			GoogleIABManager.queryInventoryFailedEvent += OnRestoreTransactionsFailed;
			GoogleIABManager.billingSupportedEvent += OnBillingSupportedEvent;
			GoogleIABManager.billingNotSupportedEvent += OnBillingNotSupportedEvent;
			g_bAwaitingBillingCallback = true;
			GoogleIAB.setAutoVerifySignatures(false);
			GoogleIAB.init(GooglePlaySecret);
			LoadProducts();
			m_started = true;
		}
	}

	private void LoadProducts()
	{
		if (m_loadedProducts != null)
		{
			return;
		}
		m_loadedProducts = new BaseCampProducts[m_storeProductDefs.Length];
		for (int i = 0; i < m_loadedProducts.Length; i++)
		{
			m_loadedProducts[i] = ScriptableObject.CreateInstance<BaseCampProducts>();
			int num = m_storeProductDefs[i].products.Length;
			m_loadedProducts[i].products = new BaseCampProducts.ProductData[num];
			for (int j = 0; j < num; j++)
			{
				BaseCampProducts.ProductData productData = m_storeProductDefs[i].products[j];
				BaseCampProducts.ProductData productData2 = new BaseCampProducts.ProductData();
				productData.CopyTo(productData2);
				m_loadedProducts[i].products[j] = productData2;
			}
		}
		m_loadedGemProducts = null;
		m_saleItem = null;
	}

	public BaseCampProducts GetProducts(BaseCampProducts.StoreCategory Category)
	{
		if (!m_started)
		{
			Start();
		}
		BaseCampProducts result = null;
		for (int i = 0; i < m_loadedProducts.Length; i++)
		{
			if (m_loadedProducts[i].products[0].Category == Category)
			{
				result = m_loadedProducts[i];
				break;
			}
		}
		return result;
	}

	public BaseCampProducts[] GetAllProducts()
	{
		if (!m_started)
		{
			Start();
		}
		return m_loadedProducts;
	}

	public GemStoreProduct GetExchangeProducts()
	{
		return m_loadedGemProducts;
	}

	public void FetchExchangeProducts()
	{
		if (Application.platform != RuntimePlatform.IPhonePlayer)
		{
			StartCoroutine("EditorProductFetch");
		}
	}

	private IEnumerator EditorProductFetch()
	{
		yield return new WaitForSeconds(3f);
		List<GemStoreProduct.GemStoreProductData> newProducts = new List<GemStoreProduct.GemStoreProductData>();
		for (int iProd = 0; iProd < m_gemProductDefs.products.Length; iProd++)
		{
			GemStoreProduct.GemStoreProductData srcProd = m_gemProductDefs.products[iProd];
			GemStoreProduct.GemStoreProductData newProd = new GemStoreProduct.GemStoreProductData(srcProd);
			newProducts.Add(newProd);
		}
		m_loadedGemProducts = ScriptableObject.CreateInstance<GemStoreProduct>();
		m_loadedGemProducts.products = newProducts.ToArray();
		if (StoreProductManager.OnExchangeProductsReceived != null)
		{
			StoreProductManager.OnExchangeProductsReceived(true);
		}
	}

	public BaseCampProducts.ProductData FindProduct(string Identifier)
	{
		BaseCampProducts.ProductData result = null;
		for (int i = 0; i < m_loadedProducts.Length; i++)
		{
			for (int j = 0; j < m_loadedProducts[i].products.Length; j++)
			{
				if (m_loadedProducts[i].products[j].Identifier == Identifier)
				{
					result = m_loadedProducts[i].products[j];
					break;
				}
			}
		}
		return result;
	}

	private void UpdateSalesFromBedrock()
	{
		m_saleItem = null;
		Dictionary<string, string> resourceDictionary = null;
		if (!Bedrock.GetRemoteUserResources("itemForSale", out resourceDictionary))
		{
			return;
		}
		string fromResourceDictionaryAsString = Bedrock.GetFromResourceDictionaryAsString(resourceDictionary, "item", string.Empty);
		if (string.IsNullOrEmpty(fromResourceDictionaryAsString))
		{
			return;
		}
		BaseCampProducts.ProductData productData = FindProduct(fromResourceDictionaryAsString);
		if (productData != null)
		{
			m_originalSaleItem = new BaseCampProducts.ProductData();
			productData.CopyTo(m_originalSaleItem);
			m_saleItem = productData;
			m_saleItem.UpdateFromBedrock(resourceDictionary);
			string fromResourceDictionaryAsString2 = Bedrock.GetFromResourceDictionaryAsString(resourceDictionary, "startDate", string.Empty);
			if (!uint.TryParse(fromResourceDictionaryAsString2, out m_saleStart))
			{
				m_saleStart = 0u;
			}
			string fromResourceDictionaryAsString3 = Bedrock.GetFromResourceDictionaryAsString(resourceDictionary, "duration", string.Empty);
			if (!uint.TryParse(fromResourceDictionaryAsString3, out m_saleDuration))
			{
				m_saleDuration = 0u;
			}
		}
	}

	public void UpdateProductsFromBedrock()
	{
		if (!m_started)
		{
			Start();
		}
		for (int i = 0; i < m_loadedProducts.Length; i++)
		{
			for (int j = 0; j < m_loadedProducts[i].products.Length; j++)
			{
				BaseCampProducts.ProductData productData = m_loadedProducts[i].products[j];
				Dictionary<string, string> resourceDictionary = null;
				if (Bedrock.GetRemoteUserResources(productData.Identifier, out resourceDictionary))
				{
					productData.UpdateFromBedrock(resourceDictionary);
				}
			}
		}
		UpdateSalesFromBedrock();
		if (BaseCampController.Instance != null)
		{
			BaseCampController.Instance.Refresh();
		}
		m_loadedGemProducts = null;
		m_receiptVerificationServerURI = Bedrock.GetRemoteVariableAsString("receiptVerifyURI", m_receiptVerificationServerURI);
		if (StoreProductManager.OnProductsUpdated != null)
		{
			StoreProductManager.OnProductsUpdated();
		}
	}

	public void BuyExchangeProduct(string Identifier)
	{
		if (Application.platform != RuntimePlatform.IPhonePlayer)
		{
			if (Application.platform == RuntimePlatform.Android)
			{
				GamePurchasedItem = Identifier;
				GoogleIAB.purchaseProduct(Identifier);
			}
			else
			{
				StartCoroutine(EditorBuyExchangeProduct(Identifier));
			}
		}
	}

	private IEnumerator EditorBuyExchangeProduct(string Identifier)
	{
		yield return new WaitForSeconds(3f);
		if (StoreProductManager.OnBuyExchangeSuccess != null)
		{
			StoreProductManager.OnBuyExchangeSuccess(Identifier);
		}
	}

	public void RestorePreviousPurchases()
	{
		m_loadedGemProducts = null;
		GoogleIAB.queryInventory(GoogleProductSkus);
	}

	public GemStoreProduct.GemStoreProductData FindSourceGemProduct(string Identifier)
	{
		GemStoreProduct.GemStoreProductData result = null;
		for (int i = 0; i < m_gemProductDefs.products.Length; i++)
		{
			if (m_gemProductDefs.products[i].Identifier == Identifier)
			{
				result = m_gemProductDefs.products[i];
				break;
			}
		}
		return result;
	}

	public string DecodeHtmlChars(string aText)
	{
		string[] array = aText.Split(new string[1] { "&#x" }, StringSplitOptions.None);
		for (int i = 1; i < array.Length; i++)
		{
			int num = array[i].IndexOf(';');
			string value = array[i].Substring(0, num);
			try
			{
				int num2 = Convert.ToInt32(value, 16);
				array[i] = (char)num2 + array[i].Substring(num + 1);
			}
			catch
			{
			}
		}
		return string.Join(string.Empty, array);
	}

	private void KFPurchaseUpdatesSucess(List<string> aRevokedItems, List<AmazonReceipt> aItemList)
	{
		StoreLog("KFPurchaseUpdatesSucess ");
		StoreLog("num items: " + aItemList.Count + " revoked: " + aRevokedItems.Count);
		foreach (AmazonReceipt aItem in aItemList)
		{
			if (aItem.sku == TreasureUpgradeIdentifier)
			{
				TBFUtils.DebugLog("Restored treasure upgrade");
				SecureStorage.Instance.SetItemCount(TreasureUpgradeIdentifier, 1);
			}
			StoreLog("KFitem " + aItem.sku);
		}
	}

	private void KFItemDataRequestFinished(List<string> aUnavailableSKU, List<AmazonItem> aItemList)
	{
		StoreLog("KFItemDataRequestFinished ");
		StoreLog("num items: " + aItemList.Count + " Unavailable: " + aUnavailableSKU.Count);
		bool obj = false;
		if (aItemList.Count > 0)
		{
			List<GemStoreProduct.GemStoreProductData> list = new List<GemStoreProduct.GemStoreProductData>();
			foreach (AmazonItem aItem in aItemList)
			{
				StoreLog("Received: " + aItem.ToString());
				GemStoreProduct.GemStoreProductData gemStoreProductData = FindSourceGemProduct(aItem.sku);
				if (gemStoreProductData != null)
				{
					GemStoreProduct.GemStoreProductData gemStoreProductData2 = new GemStoreProduct.GemStoreProductData(gemStoreProductData);
					Regex regex = new Regex("([\\d,.]+)");
					Match match = regex.Match(aItem.price);
					if (match.Success)
					{
						gemStoreProductData2.Price = match.Groups[1].Value;
						string aText = aItem.price.Replace(gemStoreProductData2.Price, " ");
						gemStoreProductData2.CurrencySymbol = DecodeHtmlChars(aText);
					}
					gemStoreProductData.Price = gemStoreProductData2.Price;
					gemStoreProductData.CurrencySymbol = " ";
					Dictionary<string, string> resourceDictionary = null;
					if (Bedrock.GetRemoteUserResources(gemStoreProductData2.Identifier, out resourceDictionary))
					{
						gemStoreProductData2.UpdateFromBedrock(resourceDictionary);
					}
					list.Add(gemStoreProductData2);
				}
			}
			m_loadedGemProducts = ScriptableObject.CreateInstance<GemStoreProduct>();
			m_loadedGemProducts.products = list.ToArray();
			obj = true;
		}
		else
		{
			m_loadedGemProducts = null;
		}
		if (StoreProductManager.OnExchangeProductsReceived != null)
		{
			StoreProductManager.OnExchangeProductsReceived(obj);
		}
	}

	private void KFItemDataRequestFailed()
	{
		StoreLog("KFItemDataRequestFailed");
	}

	private void KFPurchaseUpdatesFailed()
	{
		StoreLog("KFPurchaseUpdatesFailed");
	}

	private void OnPurchaseFailKF(string error)
	{
		StoreLog("Purchase failed: " + error);
		if (StoreProductManager.OnBuyExchangeFailed != null)
		{
			StoreProductManager.OnBuyExchangeFailed(error);
		}
	}

	private void OnPurchaseSuccessKF(AmazonReceipt aRCT)
	{
		StoreLog("Purchase success: " + aRCT.sku);
		if (StoreProductManager.OnBuyExchangeSuccess != null)
		{
			StoreProductManager.OnBuyExchangeSuccess(aRCT.sku);
		}
		OnPurchaseVerificationAmazonRCT(aRCT);
	}

	private void OnPurchaseFail(string error)
	{
		StoreLog("Purchase failed: " + error);
		if (StoreProductManager.OnBuyExchangeFailed != null)
		{
			StoreProductManager.OnBuyExchangeFailed(error);
		}
	}

	public void OnPurchaseCancel(string error, string payload)
	{
		StoreLog("Purchase cancelled: " + error);
		if (StoreProductManager.OnBuyExchangeFailed != null)
		{
			StoreProductManager.OnBuyExchangeFailed("cancelled");
		}
	}

	public void OnRestoreTransactionsFailed(string error)
	{
		StoreLog("Restore Transactions Failed: " + error);
		if (StoreProductManager.OnRestorePurchasesFailed != null)
		{
			StoreProductManager.OnRestorePurchasesFailed(error);
		}
	}

	public void OnRestoreTransactionsFinished(List<GooglePurchase> purchases, List<GoogleSkuInfo> skus)
	{
		mPurchases = purchases;
		FixIABv3Issues();
		if (purchases != null)
		{
			foreach (GooglePurchase purchase in purchases)
			{
				if (purchase.productId == TreasureUpgradeIdentifier)
				{
					SecureStorage.Instance.SetItemCount(TreasureUpgradeIdentifier, 1);
				}
			}
		}
		if (StoreProductManager.OnRestorePurchasesFinished != null)
		{
			StoreProductManager.OnRestorePurchasesFinished();
		}
	}

	private void OnPurchaseSuccessful(GooglePurchase gp)
	{
		StoreLog("Purchase success: orderId = " + gp.orderId + ", productId = " + gp.productId);
		if (gp.productId.ToLower().Contains("gems"))
		{
			GoogleIAB.consumeProduct(gp.productId);
		}
		if (StoreProductManager.OnBuyExchangeSuccess != null)
		{
			StoreProductManager.OnBuyExchangeSuccess(gp.productId);
		}
	}

	private void OnConsumePurchaseSuccessful(GooglePurchase gp)
	{
		StoreLog("Consume successful: " + gp.productId);
		Debug.Log("Consume successful: " + gp.productId);
		FixIABv3Issues();
	}

	private void OnConsumePurchaseFailed(string error)
	{
		StoreLog("Consume failed: " + error);
		Debug.Log("Consume failed: " + error);
	}

	private IEnumerator VerifyReceipt(string json)
	{
		Hashtable hashed = json.hashtableFromJson();
		if (Application.internetReachability == NetworkReachability.NotReachable)
		{
			yield return null;
			yield break;
		}
		string serverURL = GetReceiptVerificationURL();
		string encodedtext = EncodeStringBase64(json);
		string postFields = string.Format("receipt={0}", encodedtext);
		ASCIIEncoding encoding = new ASCIIEncoding();
		byte[] postData = encoding.GetBytes(postFields);
		Request verifyReq = new Request("post", serverURL, postData);
		verifyReq.AddHeader("content-type", "application/x-www-form-urlencoded");
		verifyReq.Send();
		while (!verifyReq.isDone)
		{
			yield return null;
		}
		if (verifyReq.response != null && verifyReq.response.status == 200)
		{
			StoreLog("Encoded: " + verifyReq.response.Text);
			string decodedText = DecodeStringBase64(verifyReq.response.Text);
			StoreLog("Decoded: " + decodedText);
			if (decodedText.Equals(GamePurchasedItem))
			{
				SwrveEventsPurchase.ReceiptVerifySuccess(GamePurchasedItem);
				SecureStorage.Instance.HasFailedReceiptVerification = false;
			}
			else
			{
				SwrveEventsPurchase.ReceiptVerifyFailed(GamePurchasedItem, 0);
				SecureStorage.Instance.HasFailedReceiptVerification = true;
			}
		}
		else
		{
			StoreLog("ERROR: Invalid response received from verification server");
			SwrveEventsPurchase.ReceiptVerifyServerError();
		}
	}

	private void OnPurchaseVerificationJSON(string json)
	{
		if (!TBFUtils.Is256mbDevice() && !string.IsNullOrEmpty(GetReceiptVerificationURL()))
		{
			StartCoroutine(VerifyReceipt(json));
		}
	}

	private IEnumerator VerifyReceiptAmazon(AmazonReceipt rct)
	{
		if (Application.internetReachability == NetworkReachability.NotReachable)
		{
			yield return null;
			yield break;
		}
		string serverURL = GetReceiptVerificationURL();
		string encodedtext = EncodeStringBase64(rct.toJson());
		string postFields = string.Format("receipt={0}", encodedtext);
		ASCIIEncoding encoding = new ASCIIEncoding();
		byte[] postData = encoding.GetBytes(postFields);
		Request verifyReq = new Request("post", serverURL, postData);
		verifyReq.AddHeader("content-type", "application/x-www-form-urlencoded");
		verifyReq.Send();
		while (!verifyReq.isDone)
		{
			yield return null;
		}
		if (verifyReq.response != null && verifyReq.response.status == 200)
		{
			StoreLog("Encoded: " + verifyReq.response.Text);
			string decodedText = DecodeStringBase64(verifyReq.response.Text);
			StoreLog("Decoded: " + decodedText);
			if (decodedText.Equals(GamePurchasedItem))
			{
				SwrveEventsPurchase.ReceiptVerifySuccess(GamePurchasedItem);
				SecureStorage.Instance.HasFailedReceiptVerification = false;
			}
			else
			{
				SwrveEventsPurchase.ReceiptVerifyFailed(GamePurchasedItem, 0);
				SecureStorage.Instance.HasFailedReceiptVerification = true;
			}
		}
		else
		{
			StoreLog("ERROR: Invalid response received from verification server");
			SwrveEventsPurchase.ReceiptVerifyServerError();
		}
	}

	private void OnPurchaseVerificationAmazonRCT(AmazonReceipt rct)
	{
		if (!TBFUtils.Is256mbDevice() && !string.IsNullOrEmpty(GetReceiptVerificationURL()))
		{
			StartCoroutine(VerifyReceiptAmazon(rct));
		}
	}

	private void OnBillingSupportedEvent()
	{
		StoreLog("billing supported");
		g_bIABEnabled = true;
		g_bAwaitingBillingCallback = false;
		GoogleIAB.queryInventory(GoogleProductSkus);
	}

	private void OnBillingNotSupportedEvent(string error)
	{
		StoreLog("billing NOT supported, error: " + ((!string.IsNullOrEmpty(error)) ? error : "unknown"));
		g_bIABEnabled = false;
		g_bAwaitingBillingCallback = false;
	}

	private void ConsumeProductIfOwned(string bundleId)
	{
		if (mPurchases == null || mPurchases.Count <= 0)
		{
			return;
		}
		int i = 0;
		for (int count = mPurchases.Count; i < count; i++)
		{
			if (mPurchases[i].productId == bundleId)
			{
				GoogleIAB.consumeProduct(bundleId);
				break;
			}
		}
	}

	private void FixIABv3Issues()
	{
		if (PlayerPrefs.GetInt("NeedsToConsumeBundle1", 1) == 1)
		{
			ConsumeProductIfOwned(Bundle1Indentifier);
			PlayerPrefs.SetInt("NeedsToConsumeBundle1", 0);
			PlayerPrefs.Save();
		}
		else if (PlayerPrefs.GetInt("NeedsToConsumeBundle2", 1) == 1)
		{
			ConsumeProductIfOwned(Bundle2Indentifier);
			PlayerPrefs.SetInt("NeedsToConsumeBundle2", 0);
			PlayerPrefs.Save();
		}
		else if (PlayerPrefs.GetInt("NeedsToConsumeBundle3", 1) == 1)
		{
			ConsumeProductIfOwned(Bundle3Indentifier);
			PlayerPrefs.SetInt("NeedsToConsumeBundle3", 0);
			PlayerPrefs.Save();
		}
		else if (PlayerPrefs.GetInt("NeedsToConsumeBundle4", 1) == 1)
		{
			ConsumeProductIfOwned(Bundle4Indentifier);
			PlayerPrefs.SetInt("NeedsToConsumeBundle4", 0);
			PlayerPrefs.Save();
		}
	}
}
