using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ThemeManager : SingletonMonoBehaviour
{
	private struct ThemeCheckpointRecord
	{
		public int m_seqIndex;

		public float m_distance;

		public float m_distanceLeftInTheme;
	}

	public WorldConstructionHelper.Theme m_initialTheme = WorldConstructionHelper.Theme.Mountain;

	public WorldConstructionHelper.Theme m_postInitialTheme;

	public float m_initialThemeCutoff = 600f;

	public float m_postInitialThemeCutoff = 3000f;

	public ThemeSettings[] m_themeSettings = new ThemeSettings[6]
	{
		new ThemeSettings(WorldConstructionHelper.Theme.Jungle, "tilesJungle"),
		new ThemeSettings(WorldConstructionHelper.Theme.Mountain, "tilesMountain"),
		new ThemeSettings(WorldConstructionHelper.Theme.Cave, "tilesCave"),
		new ThemeSettings(WorldConstructionHelper.Theme.SlippedMountain, "tilesSlippedMountain"),
		new ThemeSettings(WorldConstructionHelper.Theme.Minecart, "tilesMinecart"),
		new ThemeSettings(WorldConstructionHelper.Theme.Bike, "tilesBike")
	};

	public ThemeRenderSettings[] m_themeRenderSettings = new ThemeRenderSettings[7]
	{
		new ThemeRenderSettings(WorldConstructionHelper.Theme.Jungle, Color.white, true, new Color(112f, 176f, 255f), 5f, 75f),
		new ThemeRenderSettings(WorldConstructionHelper.Theme.Mountain, Color.white, true, new Color(116f, 178f, 254f), 5f, 75f),
		new ThemeRenderSettings(WorldConstructionHelper.Theme.Cave, Color.white, true, new Color(124f, 119f, 114f), 5f, 75f),
		new ThemeRenderSettings(WorldConstructionHelper.Theme.SlippedMountain, Color.white, true, new Color(124f, 119f, 114f), 5f, 75f),
		new ThemeRenderSettings(WorldConstructionHelper.Theme.Minecart, Color.white, true, new Color(106f, 21f, 11f), 5f, 75f),
		new ThemeRenderSettings(WorldConstructionHelper.Theme.Bike, Color.white, true, new Color(75f, 148f, 240f), 5f, 75f),
		new ThemeRenderSettings(WorldConstructionHelper.Theme.Menu, Color.white, false, new Color(112f, 176f, 255f), 5f, 1000f)
	};

	public ThemeSetPieceController SetPieceController = new ThemeSetPieceController();

	private ThemeState[] m_themeState;

	public float m_minThemeRestartDistance = 100f;

	public ThemeSequenceEntry[] m_themeSequence;

	private int m_themeSeqIndex = -1;

	private float m_themeSeqDistanceLeft;

	private List<ThemeCheckpointRecord> m_passedCheckpoints = new List<ThemeCheckpointRecord>();

	private int m_currentThemeFocus;

	private bool m_loadPending;

	private GameObject m_loadedPiecesObj;

	private WorldConstructionHelper.Theme m_renderTheme;

	private bool m_initialLaunchDone;

	private Color m_targetFogColour;

	private float m_targetFogStart;

	private float m_targetFogEnd;

	private Color m_targetAmbientColour;

	private float m_farClipPlane;

	public static ThemeManager Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ThemeManager>();
		}
	}

	public bool IsReady
	{
		get
		{
			int num = m_themeSettings.Length;
			for (int i = 0; i < num; i++)
			{
				if (m_themeState[i].m_loadingState != ThemeState.LoadState.LS_LOADED)
				{
					return false;
				}
			}
			return true;
		}
	}

	public PieceSet LoadedPieces
	{
		get
		{
			PieceSet pieceSet = null;
			if (m_loadedPiecesObj == null || !IsReady)
			{
				if (m_loadedPiecesObj == null)
				{
					m_loadedPiecesObj = new GameObject("CombinedPieces");
					m_loadedPiecesObj.name = "Combined-PieceSet";
					pieceSet = m_loadedPiecesObj.AddComponent<PieceSet>();
					pieceSet.Pieces = new List<PieceDescriptor>();
				}
				else
				{
					pieceSet = m_loadedPiecesObj.GetComponent<PieceSet>();
					pieceSet.Pieces.Clear();
				}
				m_loadedPiecesObj.transform.parent = base.gameObject.transform;
				int num = m_themeSettings.Length;
				for (int i = 0; i < num; i++)
				{
					if (m_themeState[i].m_loadingState == ThemeState.LoadState.LS_LOADED)
					{
						pieceSet.Pieces.AddRange(m_themeState[i].m_parentPieceSet.Pieces);
					}
				}
				pieceSet.Refresh();
			}
			else
			{
				pieceSet = m_loadedPiecesObj.GetComponent<PieceSet>();
			}
			return pieceSet;
		}
	}

	public WorldConstructionHelper.Theme TransitionTheme
	{
		get
		{
			int num = GetNextTheme();
			if (num == -1)
			{
				Debug.LogWarning("No theme found, so defaulting to first available");
				num = 0;
			}
			return m_themeSettings[num].m_theme;
		}
	}

	protected override void AwakeOnce()
	{
		if (Instance == this)
		{
			UnityEngine.Object.DontDestroyOnLoad(base.gameObject);
			int num = m_themeSettings.Length;
			m_themeState = new ThemeState[num];
			for (int i = 0; i < num; i++)
			{
				m_themeState[i] = new ThemeState();
			}
		}
	}

	private void Start()
	{
		LoadResidentThemes();
	}

	private void Update()
	{
		bool flag = false;
		AuthoredLevelController authoredLevelController = AuthoredLevelController.Instance();
		if (authoredLevelController != null)
		{
			flag = authoredLevelController.IsGlobalWorldActive();
		}
		if (!flag)
		{
			UpdateThemeTimers();
			SetPieceController.Update();
		}
		UpdateRenderSettings();
	}

	public bool IsInMineCart()
	{
		if ((bool)LevelGenerator.Instance() && (bool)LevelGenerator.Instance().GetCurrentPiece())
		{
			return LevelGenerator.Instance().GetCurrentPiece().Theme == WorldConstructionHelper.Theme.Minecart;
		}
		return false;
	}

	public bool IsOnBike()
	{
		if ((bool)LevelGenerator.Instance() && (bool)LevelGenerator.Instance().GetCurrentPiece())
		{
			return LevelGenerator.Instance().GetCurrentPiece().Theme == WorldConstructionHelper.Theme.Bike;
		}
		return false;
	}

	private void RestoreCheckpoints()
	{
		m_passedCheckpoints.Clear();
		if (!SecureStorage.Instance.HasThemeManagerState)
		{
			return;
		}
		ArrayList arrayList = SecureStorage.Instance.ThemeManagerState.arrayListFromJson();
		foreach (Hashtable item2 in arrayList)
		{
			ThemeCheckpointRecord item = new ThemeCheckpointRecord
			{
				m_distance = float.Parse(item2["dist"].ToString()),
				m_seqIndex = int.Parse(item2["seqIndex"].ToString()),
				m_distanceLeftInTheme = float.Parse(item2["left"].ToString())
			};
			m_passedCheckpoints.Add(item);
		}
	}

	private void SaveCheckpoints()
	{
		ArrayList arrayList = new ArrayList();
		for (int i = 0; i < m_passedCheckpoints.Count; i++)
		{
			Hashtable hashtable = new Hashtable();
			hashtable["seqIndex"] = m_passedCheckpoints[i].m_seqIndex;
			hashtable["dist"] = m_passedCheckpoints[i].m_distance;
			hashtable["left"] = m_passedCheckpoints[i].m_distanceLeftInTheme;
			arrayList.Add(hashtable);
		}
		SecureStorage.Instance.ThemeManagerState = arrayList.toJson();
	}

	private int FindPassedCheckpoint(float currentDistance)
	{
		int result = -1;
		for (int i = 0; i < m_passedCheckpoints.Count; i++)
		{
			if (currentDistance == m_passedCheckpoints[i].m_distance)
			{
				result = i;
				break;
			}
		}
		return result;
	}

	private void AddUniqueCheckpoint(float checkDist, int themeSeqIndex, float distanceLeft)
	{
		int num = FindPassedCheckpoint(checkDist);
		if (num != -1)
		{
			return;
		}
		ThemeCheckpointRecord item = new ThemeCheckpointRecord
		{
			m_distance = checkDist,
			m_seqIndex = themeSeqIndex,
			m_distanceLeftInTheme = Mathf.Max(distanceLeft, m_minThemeRestartDistance)
		};
		bool flag = false;
		for (int i = 0; i < m_passedCheckpoints.Count; i++)
		{
			if (checkDist < m_passedCheckpoints[i].m_distance)
			{
				m_passedCheckpoints.Insert(i, item);
				flag = true;
				break;
			}
		}
		if (!flag)
		{
			m_passedCheckpoints.Add(item);
		}
	}

	public void OnLevelReset(float currentDistance)
	{
		RestoreCheckpoints();
		m_themeSeqIndex = -1;
		m_themeSeqDistanceLeft = 0f;
		if (currentDistance < m_postInitialThemeCutoff)
		{
			if (currentDistance < m_initialThemeCutoff)
			{
				m_currentThemeFocus = FindTheme(m_initialTheme);
			}
			else
			{
				m_currentThemeFocus = FindTheme(m_postInitialTheme);
			}
		}
		else
		{
			int num = FindPassedCheckpoint(currentDistance);
			if (num != -1)
			{
				ThemeCheckpointRecord themeCheckpointRecord = m_passedCheckpoints[num];
				m_themeSeqIndex = themeCheckpointRecord.m_seqIndex;
				m_themeSeqDistanceLeft = themeCheckpointRecord.m_distanceLeftInTheme;
				m_currentThemeFocus = FindTheme(m_themeSequence[m_themeSeqIndex].m_theme);
			}
			else
			{
				CheckPointController checkPointController = CheckPointController.Instance();
				if (checkPointController != null)
				{
					currentDistance = checkPointController.FindFurthestAvailableCheckpointForDistance(currentDistance);
				}
				currentDistance -= m_postInitialThemeCutoff;
				int num2 = 0;
				while (currentDistance > m_themeSequence[num2].m_distanceInTheme)
				{
					currentDistance -= m_themeSequence[num2].m_distanceInTheme;
					num2++;
					if (num2 >= m_themeSequence.Length)
					{
						num2 = 0;
					}
				}
				m_themeSeqIndex = num2;
				currentDistance = Mathf.Max(m_minThemeRestartDistance, currentDistance);
				m_themeSeqDistanceLeft = currentDistance;
				m_currentThemeFocus = FindTheme(m_themeSequence[num2].m_theme);
			}
		}
		SetRenderTheme(m_themeSettings[m_currentThemeFocus].m_theme, true);
		m_initialLaunchDone = false;
	}

	public void OnGameEnd()
	{
		SaveCheckpoints();
	}

	public void OnThemeChange(WorldConstructionHelper.Theme theme)
	{
		int num = -1;
		for (int i = 0; i < m_themeSettings.Length; i++)
		{
			if (m_themeSettings[i].m_theme == theme)
			{
				num = i;
				break;
			}
		}
		if (num != -1)
		{
			m_currentThemeFocus = num;
		}
		SetPieceController.ThemeChange(theme);
	}

	public void OnPassedCheckpoint()
	{
		float lastKnownDistance = WorldConstructionController.Instance().LastKnownDistance;
		lastKnownDistance = Mathf.Round(lastKnownDistance / 1000f) * 1000f;
		AddUniqueCheckpoint(lastKnownDistance, m_themeSeqIndex, Mathf.Max(m_themeSeqDistanceLeft, m_minThemeRestartDistance));
	}

	private void UpdateThemeTimers()
	{
		if (!(LevelGenerator.Instance() == null) && !(WorldConstructionController.Instance() == null))
		{
			float lastKnownDistance = WorldConstructionController.Instance().LastKnownDistance;
			if (lastKnownDistance > m_postInitialThemeCutoff && m_themeSeqIndex >= 0 && m_themeSeqIndex < m_themeSequence.Length && LevelGenerator.Instance().CurrentPieceTheme() == m_themeSequence[m_themeSeqIndex].m_theme)
			{
				m_themeSeqDistanceLeft = Mathf.Max(m_themeSeqDistanceLeft - PlayerController.Instance().GetDistanceMoved(), 0f);
			}
		}
	}

	public int GetNextTheme()
	{
		if (WorldConstructionController.Instance() == null)
		{
			return m_currentThemeFocus;
		}
		float lastKnownDistance = WorldConstructionController.Instance().LastKnownDistance;
		if (lastKnownDistance < m_postInitialThemeCutoff)
		{
			if (lastKnownDistance < m_initialThemeCutoff)
			{
				m_currentThemeFocus = FindTheme(m_initialTheme);
			}
			else
			{
				m_currentThemeFocus = FindTheme(m_postInitialTheme);
			}
		}
		else if (m_themeSeqDistanceLeft <= 0f)
		{
			int num = m_themeSeqIndex + 1;
			if (num >= m_themeSequence.Length)
			{
				num = 0;
			}
			if (HasThemeLoaded(m_themeSequence[num].m_theme))
			{
				m_themeSeqIndex = num;
				m_themeSeqDistanceLeft = m_themeSequence[m_themeSeqIndex].m_distanceInTheme;
				m_currentThemeFocus = FindTheme(m_themeSequence[m_themeSeqIndex].m_theme);
			}
			else
			{
				Debug.LogWarning("Can't change theme as it isn't loaded!!\n");
			}
		}
		return m_currentThemeFocus;
	}

	public bool HasThemeLoaded(WorldConstructionHelper.Theme iIndex)
	{
		return m_themeState[FindTheme(iIndex)].m_loadingState == ThemeState.LoadState.LS_LOADED;
	}

	private void LoadResidentThemes()
	{
		ThemeSettings[] themeSettings = m_themeSettings;
		foreach (ThemeSettings themeSettings2 in themeSettings)
		{
			StartCoroutine(LoadTheme(themeSettings2.m_theme));
		}
	}

	private int FindTheme(WorldConstructionHelper.Theme ThemeToFind)
	{
		int result = -1;
		int num = m_themeSettings.Length;
		for (int i = 0; i < num; i++)
		{
			if (m_themeSettings[i].m_theme == ThemeToFind)
			{
				result = i;
				break;
			}
		}
		return result;
	}

	private IEnumerator LoadTheme(WorldConstructionHelper.Theme ThemeToLoad)
	{
		while (m_loadPending)
		{
			yield return null;
		}
		m_loadPending = true;
		int iTheme = FindTheme(ThemeToLoad);
		m_themeState[iTheme].m_loadingState = ThemeState.LoadState.LS_LOADING;
		yield return Application.LoadLevelAdditiveAsync(m_themeSettings[iTheme].m_scene);
		string NewPieceSetName = "PieceSet-" + ThemeToLoad;
		PieceSet ThemePieceSet = null;
		while (ThemePieceSet == null)
		{
			UnityEngine.Object[] pieceSets = Resources.FindObjectsOfTypeAll(typeof(PieceSet));
			UnityEngine.Object[] array = pieceSets;
			for (int i = 0; i < array.Length; i++)
			{
				PieceSet newSet = (PieceSet)array[i];
				if (newSet.name == NewPieceSetName)
				{
					ThemePieceSet = newSet;
					break;
				}
			}
			yield return null;
		}
		if (ThemePieceSet != null)
		{
			ThemePieceSet.transform.parent = base.gameObject.transform;
			m_themeState[iTheme].m_parentPieceSet = ThemePieceSet;
			ThemeSetPieceEntry entry = SetPieceController.FindSetPieceForTheme(ThemeToLoad);
			if (entry != null)
			{
				yield return Application.LoadLevelAdditiveAsync(entry.AuthoredSetPieceScene);
				AuthoredLevelLayoutController[] authoredSections = UnityEngine.Object.FindObjectsOfType(typeof(AuthoredLevelLayoutController)) as AuthoredLevelLayoutController[];
				foreach (AuthoredLevelLayoutController authoredSetPiece in authoredSections)
				{
					if (entry.Theme.ToString() == authoredSetPiece.AuthoredLevelName)
					{
						authoredSetPiece.transform.parent = ThemePieceSet.transform;
						ThemePieceSet.AuthoredSetPieces = authoredSetPiece;
						entry.SetPieceSet(ThemePieceSet);
					}
				}
			}
			UnityEngine.Object.Destroy(m_loadedPiecesObj);
			m_loadedPiecesObj = null;
			if (UnloadThemeAsset(ThemeToLoad))
			{
				for (int iPiece = 0; iPiece < ThemePieceSet.Pieces.Count; iPiece++)
				{
					PieceDescriptor pd = ThemePieceSet.Pieces[iPiece];
					Component[] mf = pd.GetComponentsInChildren(typeof(MeshFilter), true);
					for (int iMesh = 0; iMesh < mf.Length; iMesh++)
					{
						MeshFilter mesh = (MeshFilter)mf[iMesh];
						if (!mesh.name.Contains("ropeNode"))
						{
							Resources.UnloadAsset(mesh.sharedMesh);
						}
					}
				}
			}
		}
		else
		{
			Debug.LogError("Unable to find PieceSet " + NewPieceSetName);
		}
		if (TBFUtils.Is256mbDevice())
		{
			Resources.UnloadUnusedAssets();
			GC.Collect();
		}
		m_themeState[iTheme].m_loadingState = ThemeState.LoadState.LS_LOADED;
		TBFUtils.DebugLog("Loaded theme" + iTheme);
		m_loadPending = false;
		yield return null;
	}

	public WorldConstructionHelper.Theme[] LoadedThemes()
	{
		List<WorldConstructionHelper.Theme> list = new List<WorldConstructionHelper.Theme>();
		int num = m_themeSettings.Length;
		for (int i = 0; i < num; i++)
		{
			if (m_themeState[i].m_loadingState == ThemeState.LoadState.LS_LOADED)
			{
				list.Add(m_themeSettings[i].m_theme);
			}
		}
		return list.ToArray();
	}

	public string[] GetThemeScenes()
	{
		List<string> list = new List<string>();
		ThemeSettings[] themeSettings = m_themeSettings;
		foreach (ThemeSettings themeSettings2 in themeSettings)
		{
			list.Add(themeSettings2.m_scene);
		}
		return list.ToArray();
	}

	public bool AllPiecesLoaded()
	{
		bool result = true;
		int num = m_themeSettings.Length;
		for (int i = 0; i < num; i++)
		{
			if (m_themeState[i].m_loadingState != ThemeState.LoadState.LS_LOADED)
			{
				result = false;
				break;
			}
		}
		return result;
	}

	public WorldConstructionHelper.Theme GetRenderTheme()
	{
		return m_renderTheme;
	}

	public void SetRenderTheme(WorldConstructionHelper.Theme theme, bool Immediate)
	{
		m_renderTheme = theme;
		if (Immediate)
		{
			int renderTheme = (int)m_renderTheme;
			RenderSettings.fog = m_themeRenderSettings[renderTheme].m_fogEnabled;
			RenderSettings.fogColor = m_themeRenderSettings[renderTheme].m_fogColour;
			RenderSettings.fogStartDistance = m_themeRenderSettings[renderTheme].m_fogStart;
			RenderSettings.fogEndDistance = m_themeRenderSettings[renderTheme].m_fogEnd;
			RenderSettings.ambientLight = m_themeRenderSettings[renderTheme].m_ambientColour;
		}
	}

	private void UpdateRenderSettings()
	{
		int renderTheme = (int)m_renderTheme;
		RenderSettings.fogMode = FogMode.Linear;
		RenderSettings.fog = m_themeRenderSettings[renderTheme].m_fogEnabled;
		RenderSettings.fogColor = Color.Lerp(RenderSettings.fogColor, m_themeRenderSettings[renderTheme].m_fogColour, Time.deltaTime);
		RenderSettings.fogStartDistance = Mathf.Lerp(RenderSettings.fogStartDistance, m_themeRenderSettings[renderTheme].m_fogStart, Time.deltaTime);
		RenderSettings.fogEndDistance = Mathf.Lerp(RenderSettings.fogEndDistance, m_themeRenderSettings[renderTheme].m_fogEnd, Time.deltaTime);
		RenderSettings.ambientLight = Color.Lerp(RenderSettings.ambientLight, m_themeRenderSettings[renderTheme].m_ambientColour, Time.deltaTime);
		if (CameraManager.Instance != null)
		{
			CameraManager.Instance.MainCamera.backgroundColor = RenderSettings.fogColor;
			CameraManager.Instance.MainCamera.farClipPlane = RenderSettings.fogEndDistance;
		}
	}

	public static bool UnloadThemeAsset(WorldConstructionHelper.Theme assetTheme)
	{
		if (TBFUtils.Is256mbDevice() || (TBFUtils.Is512mbDevice() && (assetTheme == WorldConstructionHelper.Theme.Bike || assetTheme == WorldConstructionHelper.Theme.Minecart)))
		{
			return true;
		}
		return false;
	}
}
