using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TrialsDataManager : SingletonMonoBehaviour
{
	public class TrialState
	{
		public enum eMedalType
		{
			eMEDAL_NO_MEDAL = 0,
			eMEDAL_BRONZE = 1,
			eMEDAL_SILVER = 2,
			eMEDAL_GOLD = 3
		}

		public TrialsData.TrialDefinition m_srcData;

		public int m_relicStartIndex;

		public bool[] m_relicCollected;

		public bool m_completed;

		public float m_timeInSecs;

		public eMedalType BestMedalType
		{
			get
			{
				if (m_completed)
				{
					if (m_timeInSecs < m_srcData.m_fGoldTime)
					{
						return eMedalType.eMEDAL_GOLD;
					}
					if (m_timeInSecs < m_srcData.m_fSilverTime)
					{
						return eMedalType.eMEDAL_SILVER;
					}
					if (m_timeInSecs < m_srcData.m_fBronzeTime)
					{
						return eMedalType.eMEDAL_BRONZE;
					}
				}
				return eMedalType.eMEDAL_NO_MEDAL;
			}
		}

		public void SerializeLoad(string jsonIn)
		{
			Hashtable hashtable = jsonIn.hashtableFromJson();
			if (hashtable == null)
			{
				return;
			}
			bool.TryParse(hashtable["m_completed"].ToString(), out m_completed);
			float.TryParse(hashtable["m_timeInSecs"].ToString(), out m_timeInSecs);
			ArrayList arrayList = (ArrayList)hashtable["m_relicCollected"];
			if (arrayList != null)
			{
				m_relicCollected = new bool[arrayList.Count];
				for (int i = 0; i < arrayList.Count; i++)
				{
					m_relicCollected[i] = bool.Parse(arrayList[i].ToString());
				}
			}
		}

		public eMedalType MedalForTime(float fTime)
		{
			if (fTime < m_srcData.m_fGoldTime)
			{
				return eMedalType.eMEDAL_GOLD;
			}
			if (fTime < m_srcData.m_fSilverTime)
			{
				return eMedalType.eMEDAL_SILVER;
			}
			if (fTime < m_srcData.m_fBronzeTime)
			{
				return eMedalType.eMEDAL_BRONZE;
			}
			return eMedalType.eMEDAL_NO_MEDAL;
		}

		public string SerializeSave()
		{
			Hashtable hashtable = new Hashtable();
			hashtable["m_completed"] = m_completed;
			hashtable["m_timeInSecs"] = m_timeInSecs;
			ArrayList arrayList = new ArrayList();
			arrayList.AddRange(m_relicCollected);
			hashtable["m_relicCollected"] = arrayList;
			return hashtable.toJson();
		}

		public TrialState Clone()
		{
			TrialState trialState = new TrialState();
			trialState.m_completed = m_completed;
			trialState.m_timeInSecs = m_timeInSecs;
			trialState.m_relicCollected = (bool[])m_relicCollected.Clone();
			trialState.m_relicStartIndex = m_relicStartIndex;
			trialState.m_srcData = m_srcData;
			return trialState;
		}
	}

	public class TrialBoostState
	{
		public uint[] m_expectedRefillTime;

		public void SerializeLoad(string jsonIn)
		{
			if (string.IsNullOrEmpty(jsonIn))
			{
				return;
			}
			ArrayList arrayList = jsonIn.arrayListFromJson();
			if (arrayList != null)
			{
				for (int i = 0; i < arrayList.Count; i++)
				{
					m_expectedRefillTime[i] = uint.Parse(arrayList[i].ToString());
				}
			}
		}

		public string SerializeSave()
		{
			ArrayList arrayList = new ArrayList();
			arrayList.AddRange(m_expectedRefillTime);
			return arrayList.toJson();
		}
	}

	public const string TrialsBoostProduct = "tonic.refill";

	private const string kReminderName = "BurstRefillReminder";

	public TrialsData m_srcData;

	private TrialState[] m_trialState;

	private TrialBoostState m_boostState;

	private int m_nRelics;

	public static TrialsDataManager Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<TrialsDataManager>();
		}
	}

	public int NumRelicsCollected
	{
		get
		{
			int num = 0;
			for (int i = 0; i < m_trialState.Length; i++)
			{
				for (int j = 0; j < m_trialState[i].m_relicCollected.Length; j++)
				{
					if (m_trialState[i].m_relicCollected[j])
					{
						num++;
					}
				}
			}
			return num;
		}
	}

	public int MaxRelicsAvailable
	{
		get
		{
			return m_nRelics;
		}
	}

	public bool HaveCollectedAllRelics
	{
		get
		{
			return NumRelicsCollected == MaxRelicsAvailable;
		}
	}

	public int NumBoostsAvailable
	{
		get
		{
			int num = 0;
			for (int i = 0; i < m_boostState.m_expectedRefillTime.Length; i++)
			{
				if (IsBoostAvailable(i))
				{
					num++;
				}
			}
			if (SecureStorage.Instance.GetItemCount("tonic.refill") != num)
			{
				SecureStorage.Instance.SetItemCount("tonic.refill", num);
			}
			return num;
		}
	}

	public int MaxBoostsAvailable
	{
		get
		{
			return m_boostState.m_expectedRefillTime.Length;
		}
	}

	public float BoostTime
	{
		get
		{
			return m_srcData.m_burstTonic.m_burstTonicDuration;
		}
	}

	public float BoostSpeedMultiplier
	{
		get
		{
			return m_srcData.m_burstTonic.m_burstTonicSpeedMultiplier;
		}
	}

	public uint TimeUntilNextBoostRefill
	{
		get
		{
			uint num = uint.MaxValue;
			for (int i = 0; i < m_boostState.m_expectedRefillTime.Length; i++)
			{
				if (!IsBoostAvailable(i) && m_boostState.m_expectedRefillTime[i] < num)
				{
					num = m_boostState.m_expectedRefillTime[i];
				}
			}
			uint result = 0u;
			if (num != uint.MaxValue)
			{
				uint secondsSinceUnixEpoch = TimeUtils.GetSecondsSinceUnixEpoch(DateTime.Now);
				result = TimeUtils.GetSecondsSince(secondsSinceUnixEpoch, num);
			}
			return result;
		}
	}

	protected override void AwakeOnce()
	{
		UnityEngine.Object.DontDestroyOnLoad(base.gameObject);
		int num = 0;
		List<TrialState> list = new List<TrialState>();
		for (int i = 0; i < m_srcData.m_trialGroups.Length; i++)
		{
			for (int j = 0; j < m_srcData.m_trialGroups[i].m_trials.Length; j++)
			{
				TrialState trialState = new TrialState();
				TrialsData.TrialDefinition trialDefinition = (trialState.m_srcData = m_srcData.m_trialGroups[i].m_trials[j]);
				trialState.m_relicStartIndex = num;
				trialState.m_relicCollected = new bool[trialDefinition.m_numCollectables];
				list.Add(trialState);
				num += trialDefinition.m_numCollectables;
			}
		}
		m_trialState = list.ToArray();
		m_nRelics = num;
		int maxBurstTonics = m_srcData.m_burstTonic.m_maxBurstTonics;
		m_boostState = new TrialBoostState();
		m_boostState.m_expectedRefillTime = new uint[maxBurstTonics];
		for (int k = 0; k < maxBurstTonics; k++)
		{
			m_boostState.m_expectedRefillTime[k] = 0u;
		}
		SerializeLoad();
	}

	private void SerializeLoad()
	{
		for (int i = 0; i < m_trialState.Length; i++)
		{
			TrialState trialState = m_trialState[i];
			string trialState2 = SecureStorage.Instance.GetTrialState(trialState.m_srcData.m_identifier);
			trialState.SerializeLoad(trialState2);
		}
		m_boostState.SerializeLoad(SecureStorage.Instance.TrialsBoostState);
	}

	private void SerializeSave()
	{
		for (int i = 0; i < m_trialState.Length; i++)
		{
			TrialState trialState = m_trialState[i];
			string jsonState = trialState.SerializeSave();
			SecureStorage.Instance.SetTrialState(trialState.m_srcData.m_identifier, jsonState);
		}
		SecureStorage.Instance.TrialsBoostState = m_boostState.SerializeSave();
	}

	public void Save()
	{
		CheckForAchievements();
		SerializeSave();
	}

	public int NumTrialsComplete(WorldConstructionHelper.Theme trialTheme)
	{
		int num = 0;
		for (int i = 0; i < m_srcData.m_trialGroups.Length; i++)
		{
			if (m_srcData.m_trialGroups[i].m_theme != trialTheme)
			{
				continue;
			}
			int num2 = m_srcData.m_trialGroups[i].m_trials.Length;
			for (int j = 0; j < num2; j++)
			{
				TrialState trialState = FindTrialState(m_srcData.m_trialGroups[i].m_trials[j].m_identifier);
				if (trialState != null && trialState.m_completed)
				{
					num++;
				}
			}
		}
		return num;
	}

	public void CheckForAchievements()
	{
		int num = 0;
		for (int i = 0; i < m_srcData.m_trialGroups.Length; i++)
		{
			int num2 = NumTrialsComplete(m_srcData.m_trialGroups[i].m_theme);
			AchievementManager.Instance.SetStep(m_srcData.m_trialGroups[i].m_achievementId, num2);
			num += num2;
		}
		AchievementManager.Instance.SetStep(m_srcData.m_completeAchievementId, num);
		if (num > 0)
		{
			AchievementManager.Instance.SetCompleted(m_srcData.m_singleAchievementId);
		}
		AchievementManager.Instance.SetStep(m_srcData.m_relicAchievementId, NumRelicsCollected);
		if (GameController.Instance.NumBoostsUsedLastGame >= AchievementManager.Instance.GetStepCount(m_srcData.m_burstTonic.m_maxBoostAchivementId))
		{
			AchievementManager.Instance.SetCompleted(m_srcData.m_burstTonic.m_maxBoostAchivementId);
		}
	}

	public void MarkTrialCompleted(string trialId, float fTime)
	{
		bool flag = false;
		int num = 0;
		for (int i = 0; i < m_trialState.Length; i++)
		{
			if (m_trialState[i].m_srcData.m_identifier == trialId)
			{
				if (!m_trialState[i].m_completed)
				{
					flag = true;
				}
				m_trialState[i].m_completed = true;
				if (m_trialState[i].m_timeInSecs > 0f)
				{
					m_trialState[i].m_timeInSecs = Mathf.Min(fTime, m_trialState[i].m_timeInSecs);
				}
				else
				{
					m_trialState[i].m_timeInSecs = fTime;
				}
				SwrveEventsProgression.TrialCompleted(trialId, m_trialState[i].m_timeInSecs, GameController.Instance.TotalBoostUsedLastGame);
				ReportScoreForTrial(trialId, (long)(fTime * 100f));
				if (ScoreRetriever.Instance() != null)
				{
					ScoreRetriever.Instance().UpdateMyScoreForTrial(trialId, m_trialState[i].m_timeInSecs);
				}
			}
			if (m_trialState[i].m_completed)
			{
				num++;
			}
		}
		if (flag)
		{
			SwrveEventsProgression.TrialUnlocked(num);
		}
		CheckForAchievements();
		SerializeSave();
	}

	public TrialState FindTrialState(string trialId)
	{
		TrialState result = null;
		if (trialId != null)
		{
			for (int i = 0; i < m_trialState.Length; i++)
			{
				if (m_trialState[i].m_srcData.m_identifier == trialId)
				{
					result = m_trialState[i];
					break;
				}
			}
		}
		return result;
	}

	public bool HasCollectedRelic(string trialId, int relicIndex)
	{
		bool result = false;
		TrialState trialState = FindTrialState(trialId);
		if (trialState != null && relicIndex >= trialState.m_relicStartIndex)
		{
			relicIndex -= trialState.m_relicStartIndex;
			if (relicIndex < trialState.m_relicCollected.Length)
			{
				result = trialState.m_relicCollected[relicIndex];
			}
		}
		return result;
	}

	public void CollectRelic(string trialId, int relicIndex)
	{
		TBFUtils.DebugLog("COLLECTED RELIC " + relicIndex + " for trial " + trialId);
		TrialState trialState = FindTrialState(trialId);
		if (trialState != null && relicIndex >= trialState.m_relicStartIndex)
		{
			relicIndex -= trialState.m_relicStartIndex;
			if (relicIndex < trialState.m_relicCollected.Length)
			{
				trialState.m_relicCollected[relicIndex] = true;
				SwrveEventsProgression.RelicCollected(trialId, relicIndex, NumRelicsCollected);
			}
		}
	}

	private bool IsBoostAvailable(int BoostIndex)
	{
		bool result = false;
		uint secondsSinceUnixEpoch = TimeUtils.GetSecondsSinceUnixEpoch(DateTime.Now);
		if (secondsSinceUnixEpoch > m_boostState.m_expectedRefillTime[BoostIndex])
		{
			result = true;
		}
		return result;
	}

	private uint FindLatestRefillTime()
	{
		uint num = 0u;
		if (m_boostState != null)
		{
			for (int i = 0; i < m_boostState.m_expectedRefillTime.Length; i++)
			{
				if (m_boostState.m_expectedRefillTime[i] > num)
				{
					num = m_boostState.m_expectedRefillTime[i];
				}
			}
		}
		return num;
	}

	public bool UseBoost()
	{
		bool result = false;
		for (int i = 0; i < m_boostState.m_expectedRefillTime.Length; i++)
		{
			if (IsBoostAvailable(i))
			{
				uint num = FindLatestRefillTime();
				uint secondsSinceUnixEpoch = TimeUtils.GetSecondsSinceUnixEpoch(DateTime.Now);
				if (secondsSinceUnixEpoch > num)
				{
					num = secondsSinceUnixEpoch;
				}
				num += (uint)m_srcData.m_burstTonic.m_burstTonicRefillTime;
				m_boostState.m_expectedRefillTime[i] = num;
				result = true;
				GameController.Instance.UsedBoost();
				break;
			}
		}
		return result;
	}

	public void ResetBoosts()
	{
		for (int i = 0; i < m_boostState.m_expectedRefillTime.Length; i++)
		{
			m_boostState.m_expectedRefillTime[i] = 0u;
		}
		SerializeSave();
	}

	public void ReportScoreForTrial(string strTrialID, long lTime)
	{
		MobileNetworkManager.Instance.reportScore(lTime, strTrialID);
		ScoreRetriever.Instance().GetScoresForTrial(strTrialID, true);
	}

	private void ScheduleRefillReminder()
	{
	}

	private void CancelRefillReminder()
	{
	}

	private void OnApplicationPause(bool paused)
	{
		if (paused)
		{
			ScheduleRefillReminder();
		}
		else
		{
			CancelRefillReminder();
		}
	}
}
