using System.Collections;
using UnityEngine;

public class UIMenuBackground : SingletonMonoBehaviour
{
	public UIMenuCameraParameters m_titleViewpoint;

	public UIMenuCameraParameters m_storeViewpoint;

	public UIMenuCameraParameters m_logViewpoint;

	public UIMenuCameraParameters m_intoGameViewpoint;

	public GameObject m_harryIdlePoint;

	public Light m_menuDirectionalLight;

	public float m_cameraTransitionTime = 0.5f;

	public FrontendHarry m_harry;

	public FrontendCamera m_camera;

	public FrontendMonkey m_monkey;

	public GameObject m_volcanoEruptPrefab;

	public SoundFXData m_ambientLoop;

	public GameObject m_introSfxPrefab;

	public ParticleSystem m_volcanoSmoke;

	public float m_initialExplosionTime = 1f;

	public float m_initialCameraShake = 0.1f;

	public float m_postCameraShake = 0.02f;

	private bool m_initialCameraSetting = true;

	private string m_currentStateName = string.Empty;

	private Vector3 m_oldPlayerPos = Vector3.zero;

	private GameObject m_volcanoErupt;

	private GameObject m_introSfxObj;

	private bool m_restorePreviousTheme;

	public static UIMenuBackground Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<UIMenuBackground>();
		}
	}

	public bool IsPostSplashPlaying { get; private set; }

	private IEnumerator Start()
	{
		IsPostSplashPlaying = false;
		while (GameController.Instance == null)
		{
			yield return null;
		}
		while (CameraManager.Instance == null)
		{
			yield return null;
		}
		CameraManager.Instance.gameObject.SetActiveRecursively(false);
		ThemeManager.Instance.SetRenderTheme(WorldConstructionHelper.Theme.Menu, true);
		while (GameController.Instance.IsLoading)
		{
			yield return null;
		}
		yield return null;
		if (!ShouldUseRenderTarget())
		{
			GameObject obj = GameObject.Find("/RenderTarget");
			if (obj != null)
			{
				Object.DestroyImmediate(obj);
			}
		}
	}

	private void TweenCameraTo(UIMenuCameraParameters destination)
	{
		float transitionTime = ((!m_initialCameraSetting) ? m_cameraTransitionTime : 0f);
		m_camera.SetFocus(destination, transitionTime);
		m_initialCameraSetting = false;
	}

	public void SwitchCameraFocus(string MenuName)
	{
		switch (MenuName)
		{
		case "Title":
			TweenCameraTo(m_titleViewpoint);
			break;
		case "BaseCamp":
		case "FakeStore":
			TweenCameraTo(m_storeViewpoint);
			break;
		case "FieldGuide":
			TweenCameraTo(m_logViewpoint);
			break;
		}
	}

	private bool ShouldUseRenderTarget()
	{
		return false;
	}

	private void GameRenderTargetEnable(bool enable)
	{
		if (!ShouldUseRenderTarget())
		{
			return;
		}
		GameObject gameObject = GameObject.Find("/RenderTarget");
		if (!(gameObject != null))
		{
			return;
		}
		GameRenderTarget component = gameObject.GetComponent<GameRenderTarget>();
		if (!(component != null))
		{
			return;
		}
		if (enable)
		{
			if (CameraManager.Instance != null)
			{
				component.SetCamera(CameraManager.Instance.MainCamera);
			}
		}
		else
		{
			component.SetCamera(null);
		}
	}

	private void SetVisibility(bool Visible)
	{
		Renderer[] componentsInChildren = base.gameObject.GetComponentsInChildren<Renderer>();
		Renderer[] array = componentsInChildren;
		foreach (Renderer renderer in array)
		{
			renderer.enabled = Visible;
		}
	}

	public void Show()
	{
		SetVisibility(true);
		m_menuDirectionalLight.gameObject.SetActiveRecursively(true);
		if (LevelGenerator.Instance() != null)
		{
			LevelGenerator.Instance().MainLight.gameObject.SetActiveRecursively(false);
			LevelGenerator.Instance().SetPiecesVisibility(false);
		}
		ThemeManager.Instance.SetRenderTheme(WorldConstructionHelper.Theme.Menu, true);
		PlayerController playerController = PlayerController.Instance();
		if (playerController != null)
		{
			m_oldPlayerPos = playerController.transform.position;
			playerController.transform.position = new Vector3(0f, -100000f, 0f);
		}
		GameRenderTargetEnable(false);
		if (CameraManager.Instance != null)
		{
			CameraManager.Instance.MainCamera.gameObject.active = false;
			CameraManager.Instance.gameObject.SetActiveRecursively(false);
		}
		SoundListener.Instance.AttachTo(m_camera.gameObject);
		m_camera.gameObject.SetActiveRecursively(true);
		if ((bool)PoisonHUDController.Instance())
		{
			PoisonHUDController.Instance().HideImmediately();
		}
		Component[] componentsInChildren = GetComponentsInChildren(typeof(ParticleSystem), true);
		Component[] array = componentsInChildren;
		for (int i = 0; i < array.Length; i++)
		{
			ParticleSystem particleSystem = (ParticleSystem)array[i];
			particleSystem.Play(true);
		}
		SoundManager.Instance.Play2D(m_ambientLoop);
	}

	public void Hide()
	{
		SetVisibility(false);
		m_menuDirectionalLight.gameObject.SetActiveRecursively(false);
		if (LevelGenerator.Instance() != null)
		{
			LevelGenerator.Instance().MainLight.gameObject.SetActiveRecursively(true);
			LevelGenerator.Instance().SetPiecesVisibility(true);
		}
		if (CameraManager.Instance != null)
		{
			CameraManager.Instance.gameObject.SetActiveRecursively(true);
			CameraManager.Instance.MainCamera.gameObject.active = true;
			SoundListener.Instance.AttachTo(CameraManager.Instance.MainCamera.gameObject);
		}
		GameRenderTargetEnable(true);
		m_camera.gameObject.SetActiveRecursively(false);
		if (m_restorePreviousTheme)
		{
			ThemeManager.Instance.SetRenderTheme(WorldConstructionHelper.Theme.Jungle, true);
		}
		if (m_volcanoErupt != null)
		{
			Object.Destroy(m_volcanoErupt);
			m_volcanoErupt = null;
		}
		if (m_introSfxObj != null)
		{
			Object.Destroy(m_introSfxObj);
			m_introSfxObj = null;
		}
		m_initialCameraSetting = true;
		Component[] componentsInChildren = GetComponentsInChildren(typeof(ParticleSystem));
		Component[] array = componentsInChildren;
		for (int i = 0; i < array.Length; i++)
		{
			ParticleSystem particleSystem = (ParticleSystem)array[i];
			if (particleSystem == m_volcanoSmoke)
			{
				m_volcanoSmoke.Pause();
			}
			else
			{
				particleSystem.Stop(true);
			}
		}
		m_harry.StopAllAnims();
		m_monkey.StopAllAnims();
		SoundManager.Instance.Stop2D(m_ambientLoop);
	}

	private bool IsGameState(string stateName)
	{
		return stateName == "Game" || stateName == "Results" || stateName == "Pause";
	}

	private void OnStateActivated(string newStateName)
	{
		switch (newStateName)
		{
		case "Title":
			if (m_currentStateName == "BaseCamp")
			{
				ShopToTitle();
			}
			else if (m_currentStateName == "FieldGuide")
			{
				FieldGuideToTitle();
			}
			else if (m_currentStateName == "Options")
			{
				OptionsToTitle();
			}
			else if (IsGameState(m_currentStateName))
			{
				Show();
				InitialRunOn();
			}
			else if (m_currentStateName == "Challenges")
			{
				ChallengesToTitle();
			}
			break;
		case "BaseCamp":
			if (IsGameState(m_currentStateName))
			{
				m_restorePreviousTheme = true;
				m_camera.PlayIdle();
				Show();
			}
			if (m_currentStateName == "Results")
			{
				ResultsToShop();
			}
			else
			{
				TitleToShop();
			}
			break;
		case "Options":
			if (m_currentStateName == "BaseCamp")
			{
				m_harry.ShopToTitle();
			}
			TitleToOptions();
			break;
		case "FieldGuide":
			if (IsGameState(m_currentStateName))
			{
				m_restorePreviousTheme = true;
				m_camera.PlayIdle();
				Show();
				InitialRunOn();
			}
			TitleToFieldGuide();
			break;
		case "Results":
			if (m_currentStateName == "BaseCamp" || m_currentStateName == "FieldGuide")
			{
				Hide();
				PlayerController playerController = PlayerController.Instance();
				if (playerController != null)
				{
					playerController.transform.position = m_oldPlayerPos;
				}
			}
			break;
		case "Challenges":
			if (m_currentStateName == "Results")
			{
				m_camera.PlayIdle();
				Show();
				m_harry.RunOnScreen();
				m_monkey.RunOnScreen();
				ResultsToChallenges();
			}
			else if (m_currentStateName == "BaseCamp")
			{
				m_harry.ShopToTitle();
				TitleToChallenges();
			}
			else
			{
				TitleToChallenges();
			}
			break;
		}
		m_currentStateName = newStateName;
	}

	public float PostSplashAnimLength()
	{
		float a = m_harry.IpadToTitleLen();
		float b = m_monkey.IpadToTitleLen();
		return Mathf.Max(a, b);
	}

	public void PlayPostSplashAnim()
	{
		m_camera.m_camera.nearClipPlane = 0.01f;
		m_camera.PlayIntroAnim(OnIntroCamAnimFinished);
		m_harry.IpadToTitle();
		m_monkey.IpadToTitle();
		if (m_introSfxPrefab != null)
		{
			m_introSfxObj = (GameObject)Object.Instantiate(m_introSfxPrefab);
			m_introSfxObj.transform.parent = base.transform;
		}
		IsPostSplashPlaying = true;
	}

	private void OnIntroCamAnimFinished()
	{
		m_camera.ResetCamera();
		IsPostSplashPlaying = false;
		m_camera.m_camera.nearClipPlane = 1f;
	}

	public void InitialRunOn()
	{
		m_camera.PlayIdle();
		TweenCameraTo(m_titleViewpoint);
		m_harry.RunOnScreen();
		m_monkey.RunOnScreen();
	}

	public void ShopToTitle()
	{
		m_harry.ShopToTitle();
		TweenCameraTo(m_titleViewpoint);
	}

	public void TitleToShop()
	{
		m_harry.TitleToShop();
		TweenCameraTo(m_storeViewpoint);
	}

	public void ResultsToShop()
	{
		m_harry.ResultsToShop();
		TweenCameraTo(m_storeViewpoint);
	}

	public void TitleToFieldGuide()
	{
		TweenCameraTo(m_logViewpoint);
	}

	public void TitleToOptions()
	{
		TweenCameraTo(m_logViewpoint);
	}

	public void FieldGuideToTitle()
	{
		TweenCameraTo(m_titleViewpoint);
	}

	public void OptionsToTitle()
	{
		TweenCameraTo(m_titleViewpoint);
	}

	public void TitleToChallenges()
	{
		TweenCameraTo(m_logViewpoint);
	}

	public void ChallengesToTitle()
	{
		TweenCameraTo(m_titleViewpoint);
	}

	public void ResultsToChallenges()
	{
		TweenCameraTo(m_logViewpoint);
	}

	public float TitleToGame()
	{
		StartCoroutine("OutroToGame");
		float num = Mathf.Min(m_harry.TitleToGameAnimLength(), m_camera.TitleToGameAnimLength());
		return num + m_initialExplosionTime;
	}

	private IEnumerator OutroToGame()
	{
		m_volcanoErupt = (GameObject)Object.Instantiate(m_volcanoEruptPrefab);
		m_volcanoErupt.transform.parent = base.transform;
		m_monkey.TitleToGame();
		m_camera.SetCameraShake(m_initialCameraShake);
		yield return new WaitForSeconds(m_initialExplosionTime);
		m_camera.SetCameraShake(0f);
		m_harry.TitleToGame();
		m_camera.TitleToGame();
		float waitTime = Mathf.Min(m_harry.TitleToGameAnimLength(), m_camera.TitleToGameAnimLength());
		yield return new WaitForSeconds(waitTime);
	}

	private void OnEnable()
	{
		StateManager.stateActivated += OnStateActivated;
	}

	private void OnDisable()
	{
		StateManager.stateActivated -= OnStateActivated;
	}
}
